### ISSUE TITLE
Document how to setup Yggdrasil

### ISSUE THREAD

**Issue by alichaddad** [threefoldtech/info_grid#1]
I couldn't find any steps regarding configuring Yggdrasil and adding the necessary peers to join our network. Yggdrasil official documentation is lacking as well so it would be nice to add more details.
An example for that is the documentation for Terrafrom provider: https://library.threefold.me/info/manual/#/manual3_iac/grid3_terraform/manual__terraform_caprover?id=pre-requisites. Which just declares it as a pre-requisite without providing more details or even pointing to the official documentation.

The necessary peers can be find here: https://github.com/threefoldtech/zos-config/blob/main/production.json

**Comment by xmonader** [comment]
https://github.com/threefoldtech/info_grid/commit/449698b0d7dcddffba6bff25084df70dd9379bbb please let me know if anything needs to be updated

**Comment by robvanmieghem** [comment]
It's not added in the getting started menu

**Comment by rkhamis** [comment]
should be added [here](https://github.com/threefoldtech/info_grid/commit/b7934bc77316a583e7c302cc61004aa11760fafe)

**Comment by khaledyoussef24** [comment]
you may find it here [yggdrasil](https://library.threefold.me/info/manual/#/manual__yggdrasil_client)
![Screenshot from 2023-04-10 12-57-15](https://user-images.githubusercontent.com/110984055/230889138-29846865-1292-454a-a3e3-acc20fec4069.png)
![Screenshot from 2023-04-10 12-56-57](https://user-images.githubusercontent.com/110984055/230889140-51ac1cfd-16c2-4a73-895d-9aaccac706cf.png)
