### ISSUE TITLE
Old manual links

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/info_grid#103]
### Description

These are some of the links that still redirect to the old manual and should be replaced in the future.

### [Grid Concepts](https://www2.manual.grid.tf/concepts/concepts_readme.html)

- [TF Library - Glossary](https://library.threefold.me/info/manual/#/manual__defs)

   ![image](https://github.com/threefoldtech/info_grid/assets/101194226/6ce79ba0-0347-4d45-9e6c-984c2ec57ac4)

### [ThreeFold Grid Primitives](https://www2.manual.grid.tf/concepts/grid_primitives.html#threefold-grid-primitives-empowering-your-solutions)

- All of the links in this page still redirect to the old manual.

   ![image](https://github.com/threefoldtech/info_grid/assets/101194226/e124a683-f9c1-4c1b-b10f-f453cd8605f7)

**Comment by Mik-TF** [comment]
This is part of the library to manual transfer.

There is an ongoing PR (321) on a big transfer from library to manual. See [here](https://github.com/threefoldtech/info_grid/pull/321)
Once #321 is merged we could then tackle this current issue in a new branch+PR.

Will then write back on this issue when #321 is merged.

**Comment by Mik-TF** [comment]
This issue should be fixed when #321 is merged.
The library to manual transfer should be mostly, even perhaps completely, done.

**Comment by Mik-TF** [comment]
Fixed in #321
