### ISSUE TITLE
TFT on Ethereum_Add to Manual

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/info_grid#108]
Add TFT on [Ethereum guidelines](https://forum.threefold.io/t/tft-on-ethereum-howto/3954) to [manual](https://manual.grid.tf/getstarted/TF_Token/TF_Token.html), and link the page in the old [wiki ](https://library.threefold.me/info/threefold#/tokens/threefold__token_howtos?id=manuals-on-how-to-buy-tft) as well.

**Comment by TullysInc** [comment]
@sasha-astiadi  - Unable to assign to you in this repo. Please have a look.

**Comment by sasha-astiadi** [comment]
@TullysInc no worries thank you!

**Comment by Mik-TF** [comment]
@TullysInc 
Good idea. I can add it in the manual this week.

I think we should have a whole Ethereum section on the manual. since it's a big ecosystem.
Instead of just adding it inside the buy tft section.

We could call it:
TFT on Ethereum, between Getting Started and Planetary Network.

Let me know what you two think.

**Comment by sasha-astiadi** [comment]
Hmm i think niw we realy dont have much content. it fits more under tfchain to be honest.

im writing an intro to tfchain, and one of its benefits is interoperability how it can fits to multiple blockchain, e.g. :
tft-bsc
tft eth

and this list will expand in the future as we'll get more request from community to build other cross blockchain bridges :)
so i guess it could be

tfchain - tfchain bridges - tft - eth bridge (explain) + tft - eth (how to) & eth - tft (how to)
thanks @Mik-TF

**Comment by Mik-TF** [comment]
OK good.

I will create this directory:

* tft_ethereum_manual
  * img
    * image files
  * tft_ethereum_manual.md
  
  Then we can put this in your tfchain section when you have it.

**Comment by sasha-astiadi** [comment]
perfect!

can we please add an intro paraggraph before the howto:

# TFChain  - Ethereum Bridge

The TFChain-Ethereum Bridge is a vital component within the ThreeFold ecosystem that enables seamless interoperability and communication between the ThreeFold Chain (TFChain) and the Ethereum blockchain. This bridge serves as a connection point between the decentralized and scalable TFChain network and the widely adopted Ethereum network. By establishing this bridge, users gain the ability to transfer and interact with assets and smart contracts across both networks, unlocking a plethora of new possibilities and opportunities. 

The TFChain-Ethereum Bridge significantly enhances the utility and versatility of ThreeFold's infrastructure, allowing users to leverage the strengths of both blockchains while benefiting from enhanced security, scalability, and cost-efficiency. This integration fosters a more interconnected and inclusive blockchain ecosystem, empowering developers, businesses, and users alike to access the best of both worlds and drive innovation forward.

**Comment by Mik-TF** [comment]
@sasha-astiadi 

I can add this but I think it's a bridge with Stellar, not tfchain:
https://forum.threefold.io/t/tft-on-ethereum/3928/2

**Comment by Mik-TF** [comment]
If you can adjust your paragraph, the rest is ready.

**Comment by sasha-astiadi** [comment]
@Mik-TF sorry i confused tft bridge and tfchain... so maybe the index need to change .... no longer under tfchain... but under tft / threefold token >
- threefold token
  - TFT bridges
     - TFT Stellar - BSC (We need to have a page of this one too)
     - TFT Stellar - Ethereum

**Comment by Mik-TF** [comment]
@sasha-astiadi 

Done. Here it is: https://www2.manual.grid.tf/getstarted/TF_Token/tft_toc.html

I didn't do a new section bridge for now, as we don't have Stellar BSC yet in this section.

If you want, simply make a new issue asking to add Stellar BSC bridge section and I will add it.
I try to have the issues organized this way.

Let me know what you think, in the new issue perhaps!
