### ISSUE TITLE
Add another staging subdomain

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/info_grid#109]
We are working on reorganizing the manual into a set of sub manuals that will each serve a specific audience. In order to collaborate on this without disrupting the existing branches, we'd like to have an additional staging subdomain aside from `www2`. I've created a new branch `development-split` for this purpose, and would like to have it served under `www3` or another subdomain.

Thanks!

**Comment by hossnys** [comment]
done [here](https://github.com/threefoldtech/tf_operations/issues/1687)

**Comment by scottyeager** [comment]
Thanks @hossnys!

**Comment by sabrinasadik** [comment]
Hi @scottyeager! Can I please ask that operational issues / requests are created in the tf_operations repo and to not directly assign anyone from the team? We assign during scrum based on availability. Thanks!
