### ISSUE TITLE
Cover full VMs and how to upgrade them with Terraform

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/info_grid#114]
Terraform docs don't mention distinctions between micro VMs and full VMs. Namely:
* Only the flist determines which one we get
* Full VMs ignore the rootfs field and use the first mount as their rootfs
* We can upgrade a full VM by tearing it down, leaving the disk in detached state, then reattaching disk to new VM

from manual3 issue: https://github.com/threefoldfoundation/info_manual3/issues/155

**Comment by Mik-TF** [comment]
Fix in [this PR](https://github.com/threefoldtech/info_grid/pull/337)
Will close this issue when merged
