### ISSUE TITLE
New Manual TOC

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#116]
Hi everyone,

Just to let you know that the manual has been given a new structure.
Please note that nothing has been removed from the documentation. Only the presentation changed (basically the summary.md file).

We now have those main sections:

* General information
* Farmers
* Developers
* Sysadmins

Next we will add a main section for 3bot developers.

We might need to move some sections if anyone finds out they are misplaced.

The goal of this change is to make it easier for newcomers to navigate.

This work has been done with @scottyeager.

***

If possible, we could merge this dev branch to the master branch.
@PeterNashaat
@AhmedHanafy725
Please let me know if you can do this.

***

@sasha-astiadi 
@scottyeager 
@despiegk 
@xmonader 
@0oM4R 
@brandonpille 
@ashraffouda 
@AhmedHanafy725 
@mohamedamer453 
@samtaggart 

Thanks!

**Comment by scottyeager** [comment]
I've reverted this change from the `development` branch, since it wasn't yet planned. However, this presents a nice opportunity to gather input and gain a consensus on moving ahead with the new structure. For review, I've returned the changes to the `development-split` branch. Please have a look and let us know what you think.

**Comment by sasha-astiadi** [comment]
my proposed structure:



* **Intro to TFGrid**
    * How it Works
    * The Three Layers
    * Grid Components
    * Release Notes
* **Grid Concepts**
    * Infrastructure as Code
    * Proof of Utilization
    * Proof of Capacity \
	Grace Periods
    * Cloud Pricing
    * Planetary Network
* **TFT**
    * TFT Intro
    * Buying & Storing TFT
    * Bridging TFT
* **TF Products & Services**
    * TF Connect App
    * TF Dashboard
    * TF Playground
    * TF Weblet
    * TF Portal
    * TF Explorer
    * TF Flist Hub
    * Planetary Network App
    * TFChain Bridges
    * Other Services
    * TF Web tool (zola)
    * Circle Tool
* **Prerequisites**
    * Sign up on TFConnect App
    * Buy TFT
    * Sign up on TF Dashboard
    * Explore Capacity
* **Farmer’s Guides**
    * Build a 3Node
    * Complete DIY 3Node Guides
    * Farming Optimization
    * TFT and Farming
    * Farmerbot
    * Farmers FAQ
* **Weblet** **Manuals**
    * 
* **Developer’s Guides**
    * Javascript Client
    * Go Client
    * TFGrid CLI
    * ThreeFold Chain
    * Grid Proxy
    * Flist Hub
* **System Administrator’s Guides**
    * Tutorial: Find Node
    * Tutorial: Deploy Your First VM
    * SSH Remote Connection
    * Remote Desktop and GUI
    * Deploy a Weblet
    * Terraform
    * Resources
* **Advanced Topics**
    * Terraform Provider
    * Terraform Provisioners
    * Mounts
    * Capacity Planning
    * Updates
    * Nextcloud Redundant Deployment
    * Token Transfer Keygenerator
    * Cancel contracts
    * Contract Bills Reports
    * Listing Free Public IPs
    * Redis

**Comment by Mik-TF** [comment]
Thanks for the feedback @sasha-astiadi 

Ideally, the content of the manual would be organized in few main sections (i.e. in books). (There is also a book "3Bot" that will be added soon.)

We can definitely take some of your lists and set them within the main books.
Also there can be duplicate of sections in different main books.

The goal is, let's say for a farmer, to be able to navigate within one book and find the essential information to complete a given project/task (e.g. to build a farm).

**Comment by Mik-TF** [comment]
The new architecture has been approved and is now in dev branch, soon to be in master branch too! Closing :) Thanks.

**Comment by samtaggart** [comment]
Amazing work !!!
