### ISSUE TITLE
terraform: document gateways with wireguard backends

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#118]

**Comment by xmonader** [comment]
You're right indeed @mohamedamer453

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/info_grid/pull/241/files

**Comment by mohamedamer453** [comment]
Verified.

The docs were also added to the manual. https://www2.manual.grid.tf/terraform/resources/terraform_vm_gateway.html#using-gatway-name-on-private-networks-wireguard
