### ISSUE TITLE
Multiple nodes can run with the same node id

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/info_grid#122]
Farmers are sometimes backing up their nodes' seed files, and in at least one case, a farmer has accidentally brought two nodes online with the same node id. Of course this does not make economic sense and is unlikely to happen often, but it should really not be possible.

Ideally, someday node identity will be linked to hardware such that a seed file cannot be transferred. For now, I wonder if there's any simple check that can be performed, maybe around uptime reports, that won't require too much change?

**Comment by xmonader** [comment]
Fixed in 9552d6271fc77080d6f045debc7aec1939681a05
