### ISSUE TITLE
Adding a public IP range to a farm fails if one of the IPs in the mentioned range is already created.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/info_grid#123]
### Description

When the user tries to enter a specific IP range in a farm and one of the IPs in this range is already created in this farm, the creation fails when it reaches the mentioned IP without creating the rest of the IPs (if the range still includes other IPs).

### Case 1: When the duplicate IP is the first one in the range.

[TF DASHBOARD (5).webm](https://user-images.githubusercontent.com/101194226/190406729-12a7b4c2-fe22-430c-a91b-376be7ae0bda.webm)

### Case 2: When the duplicate IP is in the middle of the range.

[TF DASHBOARD (6).webm](https://user-images.githubusercontent.com/101194226/190407001-fe2d41e8-36b2-4e58-bd25-b7e49ce2a07d.webm)

**Comment by 0oM4R** [comment]
We can resolve the bug by flirting the ip range provided by the user with the already existing  ips,
then show the excluded ips with a warning message that those ips already exist

- same logic with this point, the warning message will be something like `the gateway ip can't be used as public ip`  :

    > * if the gateway Ip exists inside the entered range ? or is it ok to have it :D?
    >   for example adding range from `185.206.122.49/24` to `185.206.122.51/24` with gw IP = `185.206.122.50`
    >   ![image](https://user-images.githubusercontent.com/62248851/225310977-0f4fca66-7226-4a09-97ec-ba079453bbff.png)



- will check on the ips and ignore the gateway while filtring the entered range with the existing ips 

    > * If we have the same entered IP **AND** with the same gateway? or just check on the Ip only?


- we can't support this scenario now so will mention that on docs 

  > * If the entered IP already existed on another farm ? or its fine to have the same IP on different farms?

**Comment by 0oM4R** [comment]
after some discussion will mention these notes in docs only.

**Comment by mohamedamer453** [comment]
Verified.

Notes were added and available [here](https://www2.manual.grid.tf/dashboard/portal/dashboard_portal_ui_farming.html#add-a-public-ip-to-your-farm).
