### ISSUE TITLE
Kubernetes: `corex` option

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/info_grid#124]
### Description

There's an option in the kubernetes module called `Corex`. it's a boolean value and it's set to `false` by default.

[These](https://library.threefold.me/info/manual/#/technology/threefold__corex?id=zero-os-as-generator-for-compute-storage-network-capacity) are the only docs that i found related to it and i understood that it's a tool that allow managing the deployments remotely over the web.

I tried to deploy a K8s cluster and changing the `corex` value to true for both the master and worker. and after a successful deployment

![image](https://user-images.githubusercontent.com/101194226/229349513-43c9c2a4-6190-4a99-a35c-bf7e4ad92909.png)

I was not able to access it with the following error.

```
ssh root@300:2589:76ee:f44e:72d1:a4f:91d3:dcd4
ssh: connect to host 300:2589:76ee:f44e:72d1:a4f:91d3:dcd4 port 22: Connection refused

```
 
![image](https://user-images.githubusercontent.com/101194226/229349559-89758c85-6570-4c4b-a475-8287066c1b51.png)

![image](https://user-images.githubusercontent.com/101194226/229349595-9e38cd73-9901-4895-8e74-64323aa2bc08.png)

I'm not sure if i'm using it incorrectly or if it's not working. so it should either be documented well or removed if it's not working/used by anything else.

### Steps to reproduce

- Navigate to the `kubernetes.ts` script.
- Set the `corex` value to `true` for both the master and worker.
- `npx ts-node --project tsconfig-node.json scripts/kubernetes.ts`

**Comment by Mik-TF** [comment]
Any progress on this? Let me know if I can help. I could update the manual if needed.

**Comment by Mik-TF** [comment]
@xmonader Are we still working on this or we should close it? (Removed from 3.13 on Nov 5, 2023).

**Comment by Mik-TF** [comment]
@mohamedamer453 any progress on this? @xmonader 

Should we close it or can we work further on this and merge?

**Comment by xmonader** [comment]
will close
