### ISSUE TITLE
dev net node parking error (nodes can join any farm)

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/info_grid#125]
- Dev Net

![image](https://user-images.githubusercontent.com/44621168/187706299-604142e0-a0a1-4725-88c9-db0312060c72.png)

Node 47 Farm 11 is not one of my nodes, its welcome in the farm but i am concerned that since my farm has public ip addresses available its mis location may cause it to not deploy properly or offer addresses that it cannot serve?

**Comment by xmonader** [comment]
moved here to be flagged as a known issue

**Comment by xmonader** [comment]
@ramezsaeed please make sure that's tracked as a known issue in the manual

**Comment by Mik-TF** [comment]
@xmonader @ramezsaeed 
Is this issue fixed? I see Accepted. If yes, we can close it. Otherwise, we can finish what has to be done. I can help!

**Comment by ramezsaeed** [comment]
Not Fixed yet I think. @xmonader 
I add it in known issues

**Comment by xmonader** [comment]
Needs to be added to the known issues and documented on the wiki

**Comment by Mik-TF** [comment]
As for the document on wiki part, this can be added on this page: https://manual.grid.tf/farmers/3node_building/1_create_farm.html

But it is to be noted that we should update this page of the manual with the new dashboard coming up, and also with the new way to create a farm.

I will create an issue for this (new dashboard and farm creation method) and link this one.

@xmonader 
Let me know what you think.

**Comment by Mik-TF** [comment]
This issue is fixed when PR #362 is merged.

As for the comment above, we can update the dashboard in a new issue to close the current issue quickly.

**Comment by Mik-TF** [comment]
Fix in #362 
Closing the issue.
