### ISSUE TITLE
Farmerbot, compose log or compose logs

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#126]
In [this section](https://www2.manual.grid.tf/farmers/farmerbot/farmerbot.html#running-the-farmerbot) of the farmerbot, the command might not be the good one:

> docker compose log > farmerbot.log

It might be something like

> docker compose logs > farmerbot.log

Can we check what is the right command then I can update the documentation?

@brandonpille 
Thanks!

**Comment by brandonpille** [comment]
Indeed you're right. Here is the PR: #127

**Comment by Mik-TF** [comment]
Thanks. Closing this issue!
