### ISSUE TITLE
Add mermaid mdbook  function

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#129]
It would be nice to add the possibility to put mermaid diagrams into the mdbook.

It can be easily done by installing this: https://github.com/badboy/mdbook-mermaid

Basically, we only need to add this in the book.toml file:

```
[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
no-section-label = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

```

and add those two files: mermaid-init.js and mermaid.min.js.

***

Then, we can create diagrams.

In this example, when you click on the bridges, it leads you to the mdbook guides. This would be added in the TFT section of the guide.

```mermaid

graph LR
    A((TFChain-MainNet)) --- id1(Stellar / TFChain MainNet Bridge) --- B((Stellar Chain));
    C((TFChain-TestNet)) --- id2(Stellar / TFChain TestNet Bridge) --- B((Stellar Chain));
    B((Stellar Chain)) --- id3(Stellar / BSC Bridge) --- E((Binance Smart Chain));
    B((Stellar Chain)) --- id4(Stellar / Eth Bridge) --- D((Ethereum Chain));

    click id1 "https://www2.manual.grid.tf/threefold_token/tft_bridges/tfchain_stellar_bridge.html"
    click id2 "https://www2.manual.grid.tf/threefold_token/tft_bridges/tfchain_stellar_bridge.html"
    click id3 "https://www2.manual.grid.tf/threefold_token/tft_bridges/bsc_stellar_bridge.html"
    click id4 "https://www2.manual.grid.tf/threefold_token/tft_bridges/tft_ethereum/tft_ethereum.html"

```

**Comment by Mik-TF** [comment]
@xmonader 
Do you think this is possible?

**Comment by xmonader** [comment]
It'd be great definitely!!

**Comment by Mik-TF** [comment]
Since we decided to go forward, I did a [draft PR](https://github.com/threefoldtech/info_grid/pull/144) with the mermaid changes in the book and created an [issue](https://github.com/threefoldtech/info_grid/issues/145) to have the mermaid preprocessor installed on the web server.

Thus I close this issue. Thanks.
