### ISSUE TITLE
Transaction Fee for BSC to Stellar 

### ISSUE THREAD

**Issue by amandacaster** [threefoldtech/info_grid#134]
The transaction fee for [BSC to Stellar ](https://manual.grid.tf/TF_Farmer_Guide/TF_Complete_Farmer_Guide/farmer_guide.html?highlight=1%20TFT%20FEE#how-to-use-the-bsc-stellar-bridge) needs to be changed from 50TFTs to 100TFTs 
![photo_2023-06-15_15-10-00](https://github.com/threefoldtech/info_grid/assets/88147124/0f55b241-429c-4997-be48-716ff64cc4c6)

**Comment by Mik-TF** [comment]
This has been fixed in dev branch. It will thus be solved when we merge dev to master. Thanks!
