### ISSUE TITLE
MANUAL: go client install is outdated and repo is archived.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/info_grid#135]
Following / testdriving the new manual on the grid3-go client there are a number of issues.  The URL (content) is here: https://www3.manual.grid.tf/go/grid3_go_installation.html

- execute the command as described:  failed.

```
➜  github go get github.com/threefoldtech/grid3-go

go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```
- manually cloning the repo show that the [repo](https://github.com/threefoldtech/grid3_client_go) is archived.  Do we still want to promote usage?
<img width="1176" alt="image" src="https://github.com/threefoldtech/info_grid/assets/13766992/9aaf15d6-2e4f-4fae-85dd-59cd55f759e1">

**Comment by Mik-TF** [comment]
Fixed in [this PR](https://github.com/threefoldtech/info_grid/pull/330)
