### ISSUE TITLE
document gpu: go-client

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#154]

**Comment by xmonader** [comment]
can use https://forum.threefold.io/t/gpu-support-updates/3988 for initial content

**Comment by mohamedamer453** [comment]
Verified.

An example on deploying a VM with GPU through the go-client was added to the manual with a clear comment above each line in the example mentioning its function and it can be checked from https://www.manual.grid.tf/go/grid3_go_vm_with_gpu.html
