### ISSUE TITLE
document gpu: typescript 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#156]

**Comment by xmonader** [comment]
can use https://forum.threefold.io/t/gpu-support-updates/3988 for initial content

**Comment by xmonader** [comment]
can use https://forum.threefold.io/t/gpu-support-updates/3988 for initial content

**Comment by xmonader** [comment]
can use https://forum.threefold.io/t/gpu-support-updates/3988 for initial content

**Comment by mohamedamer453** [comment]
Verified from https://www2.manual.grid.tf/javascript/grid3_javascript_gpu_support.html

Initial docs for the gpu were added with an example on how to use the gpu from typescript client.


![image](https://github.com/threefoldtech/info_grid/assets/101194226/6e5b80d7-c704-45cc-9c96-954b983a9924)
