### ISSUE TITLE
Document zdb deployment for qsfs

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/info_grid#16]
I know there is an example for deploying a single zdb: `/src/javascript/grid3_javascript_zdb.md`
It would be a real added value if there is documentation to deploy zdb's for qsfs (4 metadata and 8+4 data)

**Comment by 0oM4R** [comment]
For now I set the zdbs count to 12, as the script deploy the zdbs only without qsfs workload, and  qsfs workload has the option to set `parity + shards` and I can't add deploying workload to the script.

**Comment by mohamedamer453** [comment]
Verified from www2.manual.grid.tf

The mentioned example for deploying zdbs for qsfs was added under the javascriptclient section https://www2.manual.grid.tf/javascript/grid3_javascript_qsfs_zdbs.html#deploying-zdbs-for-qsfs
