### ISSUE TITLE
Manual: Move where to buy and sell info to the manual

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/info_grid#162]
https://library.threefold.me/info/threefold#/tokens/threefold__how_to_buy

Right now we are linking to the above Library location from

https://manual.grid.tf/threefold_token/buy_sell_tft/buy_sell_tft.html

We should move whatever is relevant from the Library page to the manual, and generally we shouldn't link to the Library from the Manual.

**Comment by sasha-astiadi** [comment]
i'm already working on it

**Comment by sasha-astiadi** [comment]
you can find all files on 'tokens' folder, migration4 branch

<img width="221" alt="Screenshot 2023-06-28 at 16 57 15" src="https://github.com/threefoldtech/info_grid/assets/43240801/8a59849b-e2fa-4c61-ba91-93096c704d4b">
