### ISSUE TITLE
fix playground version in 3.10 release notes 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/info_grid#174]
https://github.com/threefoldtech/info_grid/blob/development/src/roadmap/releasenotes/tfgrid_release_3_10_0.md#tf-playground-v150
playground have a wrong version in the current 3.10 release notes which should be v2.0.0

**Comment by sasha-astiadi** [comment]
done on pr https://github.com/threefoldtech/info_grid/pull/175 thanks samir
