### ISSUE TITLE
Dedicated nodes discount should be updated

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/info_grid#189]
### Description

The dedicated nodes docs has an incorrect [discount value](https://manual.grid.tf/dashboard/portal/dashboard_portal_dedicated_nodes.html#billing--pricing) it's displayed as `70%` while it should be `50%` and the 50% discount can be confirmed according to the calculations applied [here](https://gist.github.com/mohamedamer453/6ac5cdac2fb35bbf3d1462e89c8bb1e7#rent-contract) in comparison to the actual value for renting the node.

![image](https://github.com/threefoldtech/info_grid/assets/101194226/eca1817f-cd35-456c-b65a-f1b1f9fe6c2a)

![image](https://github.com/threefoldtech/info_grid/assets/101194226/4384fc96-e2f5-40d5-ba5e-17c8792512bf)

and the link for discount levels redirects to the old [manual](https://library.threefold.me/info/threefold/#/tfgrid/grid/pricing?id=discount-levels). while it should redirect to https://manual.grid.tf/cloud/cloudunits_pricing.html#staking-discount

**Comment by Mik-TF** [comment]
@mohamedamer453 did the changes and it has been merged in both dev and master.
Closing this now.
