### ISSUE TITLE
Proposition: Should we add the Farming documentation?

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#20]
Should we add the farming documentation?

It is currently available here: https://mik-tf.github.io/TF_Farmer_Guide/index.html

The main sections are:

[Threefold Complete Farming Guide](https://mik-tf.github.io/TF_Farmer_Guide/TF_Complete_Farmer_Guide/farmer_guide.html)
[3node DIY Desktop](https://mik-tf.github.io/TF_Farmer_Guide/3node_diy_desktop/3node_diy_desktop.html)
[3node DIY Rack Server](https://mik-tf.github.io/TF_Farmer_Guide/3node_diy_rack_server/3node_diy_rack_server.html)

It's over 200 pages of documentation, if I remember correctly.

If yes, I can quickly pull request and add a new section "Threefold Farming" just above the "Farmerbot" section.

@xmonader
Let me know!

**Comment by xmonader** [comment]
really good suggestion!! I think we should then i'll refactor it out if needed

**Comment by Mik-TF** [comment]
@xmonader 

Good. I will pull request in dev branch with the said sections this week.
Will let you know here when it's done.

**Comment by Mik-TF** [comment]
@xmonader 

The pull request with new content is available here: https://github.com/threefoldtech/info_grid/pull/26

I'll close this issue then.
