### ISSUE TITLE
Master branch, mermaid not working

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#207]
The master branch website (www.manual.grid.tf) does not show the mermaid diagram properly, while it works on the dev branch website (www2.manual.grid.tf).

* master: https://www.manual.grid.tf/threefold_token/tft_bridges/tft_bridges.html
* dev: https://www2.manual.grid.tf/threefold_token/tft_bridges/tft_bridges.html

The master branch shows correctly the mermaid diagram when built locally (git clone, mdbook serve --port ...).

@PeterNashaat 
@xmonader 

Setting this as major since it's on the official manual.

Thanks!

**Comment by Mik-TF** [comment]
Potential help to fix this: Should we set git checkout master in the workflow?

```
          cd websites/info_grid/
          git checkout master
          git log -1
          git fetch
          git reset --hard origin/master
          mdbook build -d docs
 ```

**Comment by Mik-TF** [comment]
OK I think the fix is simple, it seems the mermaid preprocessor isn't installed on the master directory:

https://github.com/threefoldtech/info_grid/actions/runs/5615402448/job/15215611131#step:3:39

**Comment by Mik-TF** [comment]
I think we should also add git checkout for each branch, avoid the error [here](https://github.com/threefoldtech/info_grid/actions/runs/5615402448/job/15215611131#step:3:34) (line 33-35).

* Master:

```
cd websites/info_grid/
git checkout master
git log -1
git fetch
git reset --hard origin/master
mdbook build -d docs
```

***

* Dev:

```
cd websites/info_grid/
git checkout development
git log -1
git fetch
git reset --hard origin/master
mdbook build -d docs
```

***

* Dev-split:

```
cd websites/info_grid/
git checkout development-split
git log -1
git fetch
git reset --hard origin/master
mdbook build -d docs
```

**Comment by PeterNashaat** [comment]
- Updated mdbook to version v0.4.32, And diagrams working properly.
```
mdbook --version
mdbook v0.4.32
```

**Comment by Mik-TF** [comment]
Thanks @PeterNashaat.

That was FAST! Closing the issue. Have a good day.
