### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#211]
to include mermaid and mdbook-mermaid as requirements

**Comment by Mik-TF** [comment]
Good. It's done in this [PR's commit](https://github.com/threefoldtech/info_grid/commit/84bb3c530d2b479c2fd49dbc28af60d4cb6dda4e)

I only added mdbook-mermaid, as "mermaid" in itself is included in mdbook-mermaid, as I understand.
