### ISSUE TITLE
Update the docs about dedicate billing plan

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/info_grid#215]
Update the documentation for the dedicated billing plan to clarify that the billing rate is calculated hourly rather than monthly.

https://github.com/threefoldtech/tfchain/issues/800

https://manual.grid.tf/dashboard/portal/dashboard_portal_dedicated_nodes.html#billing--pricing
https://library.threefold.me/info/threefold/#/tfgrid/grid/pricing?id=discount-levels

**Comment by Mik-TF** [comment]
Concerning this, I proposed a [calculator in this issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/773)
It's noted as "later" but it might be appropriate with this current info_grid's issue.

**Comment by Mik-TF** [comment]
* Fix when #341 is merged
