### ISSUE TITLE
Shouldn't there be versions?

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/info_grid#22]
Currently there are only development and master branches.
I think it would make sense to use tags for grid versions that can be published as a release and branches for versions being worked on but not released yet so the docs can be worked on already and can be checked before a release.

**Comment by robvanmieghem** [comment]
I've been thinking a bit more on this and git tags are probably not a good solution. It would mean a new tag has to be published for every addition to the docs so they can't be kept in sync with grid versions anyway.
Branches can work though, with a main branch for the currently deployed version on mainnet and version branches for the rest.

**Comment by rkhamis** [comment]
I think for consistency, we should indeed use versions

**Comment by robvanmieghem** [comment]
> Hmm, I think maybe we can use master/main for the current release and development for the upcoming?

why not a 3.9 and 3.10 branch instead of 1 development one? It would be clear and info can already be created on the 3.10 for example and we're not constantly running behind on the docs.

It's also easier to merge

**Comment by robvanmieghem** [comment]
https://github.com/threefoldtech/info_grid/blob/master/versioning.md
