### ISSUE TITLE
integrate link checker in the workflow

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#233]
possibly https://github.com/marketplace/actions/markdown-link-check

**Comment by Mik-TF** [comment]
Once we have this link checker, we will be able to check all links before doing any PRs.

To prepare for this, I created a new and a new branch (see Update broken links above), where we check and fix all broken links.

**Comment by Mik-TF** [comment]
Note:

* The link checker should run:
  * on each push
  * once a week (as a cron job in the workflow)
  
This will ensure that external links are still valid in-between pushes.

**Comment by Mik-TF** [comment]
Current development-split branch has a working link checker workflow

* Example: https://github.com/threefoldtech/info_grid/actions/runs/6973335935/job/18977157893
* Branch: https://github.com/threefoldtech/info_grid/tree/development-split

More work might be needed, but it's to give an idea of the work done.

**Comment by Mik-TF** [comment]
Working, with @scottyeager, on a link checker to scan a whole website (dynamic or static), written in python and based on [muffet](https://pkg.go.dev/github.com/raviqqe/muffet).

We will be able to use this for all the different ThreeFold websites (threefold.io, mdbooks, etc.), as a github action for example.

Will keep this issue updated with progress. Should be available this week.

**Comment by Mik-TF** [comment]
Repo for the link checker: https://github.com/threefoldfoundation/website-link-checker
Ready to use as a python program, but we will set as a github action.

Will share progress here.

**Comment by Mik-TF** [comment]
* Fix in #302 when PR is merged
