### ISSUE TITLE
Updating master branch with dev branch

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#25]
Hi,

Can't remember when or where, but I saw there was an issue with the .yml file between master and dev branch for the manual.
This made it hard to update the master branch with the dev branch, as I read.

Is it fixed now?

There are new sections in [www2.manual.grid.tf](https://www2.manual.grid.tf/) that are not yet updated on [www.manual.grid.tf](https://manual.grid.tf/)

Last update from master branch is 3 weeks ago.
Last update from master branch is 5 days ago.

@xmonader 
Let me know if I can be of any help.
Thanks.

**Comment by xmonader** [comment]
All updated now :)
