### ISSUE TITLE
Add Bridge Verification Forum post to Manual

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#285]
@scottyeager shared a forum post on how to verify tft bridge transactions (bsc-stellar, stellar-bsc).

It would be a great addition on the TF Manual.

See the post: https://forum.threefold.io/t/how-to-verify-tft-bridge-transactions-to-bsc/3979

It could be added as a sub-section under BSC-Stellar bridge in the TFT bridge section (https://manual.grid.tf/threefold_token/tft_bridges/tft_bridges.html)

**Comment by amandacaster** [comment]
@Mik-TF & @TullysInc I have added the changes. Let me know if it is ok. The [PR](https://github.com/threefoldtech/info_grid/pull/287) has been created as well.

**Comment by amandacaster** [comment]
Thanks, @Mik-TF for the merge.
