### ISSUE TITLE
info for  creating and deleting contracts and deployments fees

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/info_grid#293]
there is no clear documentation for the billing of creating a contract and deleting a contract even generating the ssh key.
by following the amount deducted 
noticed :
creating contract costs 0.003 tft
deleting contract costs 0.002 tft
generating ssh costs 0.001 tft

balance
![image](https://github.com/threefoldtech/info_grid/assets/110984055/3573cc42-96f6-4df0-8aef-1e54328e8202)
after creating contract
![image](https://github.com/threefoldtech/info_grid/assets/110984055/73c4a2d6-b4af-464f-a552-e1af35170a75)
after deleting contract
![image](https://github.com/threefoldtech/info_grid/assets/110984055/e07d50bb-ee5e-4249-b260-68478ece4cc4)
after generating ssh key
![image](https://github.com/threefoldtech/info_grid/assets/110984055/c250b8f2-2c87-4502-9369-d9c4d0910b0a)

**Comment by Mik-TF** [comment]
Fix when #343 is merged
