### ISSUE TITLE
document perf tests

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#295]

**Comment by Mik-TF** [comment]
@xmonader 

Can you add more info here? Could perhaps work on this.
Thanks.

**Comment by xmonader** [comment]
@ramezsaeed can help with that and also can link to test cases the qa team executed

**Comment by khaledyoussef24** [comment]
documentation for perf tests are provided in 
https://github.com/threefoldtech/zos/blob/main/docs/tasks/README.md
explaining iperf , public ips, cpu performance.

test suite covering the test cases for he perftesting :
https://app.testlodge.com/a/26076/projects/40893/suites/234919

**Comment by ramezsaeed** [comment]
@xmonader @Mik-TF 
should we add this to info_grid somewhere ?

**Comment by Mik-TF** [comment]
@ramezsaeed 
I can add the perf file with the other md files (iperf, pub ip, etc.) then make a PR and write here when it's done.

Let me know if anyone wants to do it, but I think it's clear what needs to be done and I can do it quickly.

@xmonader 
@khaledyoussef24

**Comment by Mik-TF** [comment]
@xmonader 
@ramezsaeed 
@khaledyoussef24 

See [this PR](https://github.com/threefoldtech/info_grid/pull/340) for the perf test added in the manual.

We can close this issue when the PR is merged.
