### ISSUE TITLE
Update tfchain-stellard bridge documentation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/info_grid#301]
### Description

The documentation for using tfchain-stellar bridge needs to be updated with new links for the upcoming playground/dashboard and also the steps will need to be updated since polkadot extension is not used anymore

https://manual.grid.tf/threefold_token/tft_bridges/tfchain_stellar_bridge.html#how-to-use-the-tfchain-stellar-bridge

![image](https://github.com/threefoldtech/info_grid/assets/101194226/6c3bfaa5-4b06-4a00-8051-581f38a86206)

**Comment by Mik-TF** [comment]
@xmonader @mohamedamer453 

I know this is [currently blocked](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1485#issuecomment-1827726018), but the moment we have the new setup ready, I can write the documentation for this issue.

So if possible, let me know in this issue when it's time to write the docs.

**Comment by Mik-TF** [comment]
Fixed with new dashboard docs.
