### ISSUE TITLE
https://manual.grid.tf/dashboard/explorer/explorer_find_capacity.html

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/info_grid#308]
error image not shown on https://manual.grid.tf/dashboard/explorer/explorer_find_capacity.html

<img width="1081" alt="Screenshot 2023-12-04 at 13 35 10" src="https://github.com/threefoldtech/info_grid/assets/43240801/7808cf0a-dd74-4515-a7fe-45cdf173a6cd">

**Comment by Mik-TF** [comment]
@sasha-astiadi 

Noted. I will take the opportunity to add information and some edits to this page. It needs some attention.

**Comment by Mik-TF** [comment]
We can close once #309 is merged.
