### ISSUE TITLE
add notes on farmerbot and minting

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#319]
We need to state clearly the situation on farmerbot and minting.

A draft is started [here](https://github.com/threefoldtech/info_grid/compare/development...development_fbot_minting_notes).

We will need to discuss this further before publishing a final version.

@samtaggart 
@scottyeager 
@sabrinasadik 
@LeeSmet

**Comment by sabrinasadik** [comment]
Started a draft on Friday, didn't see this issue until now. Forum post was just posted: https://forum.threefold.io/t/minting-november-2023/4161

**Comment by Mik-TF** [comment]
Fix in #322
