### ISSUE TITLE
New Section: Video Gallery

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#32]
# Proposition: Add the Video Gallery in the Manual

1. Update the [video gallery post](https://forum.threefold.io/t/threefold-video-gallery/3091) with the latest videos
2. Turn the post into a new manual section and embed each video

# Format of Video Presentation

* Name of video
* Embedded URL (watchable video on the manual website)
* Date of release
* Notes (optional)

Then, the manual would include all available videos on Threefold.
It would be a good way to show the community effort as well as offer documentation quickly.

This would also include community calls, etc.

Of course, we explain that TF isn't responsibly for the content published by individuals and that people should check things for themselves.

***

It can be done quite quickly, but first I want to check here if it's alright with the manual format and if the team thinks it would be a good addition.

Once/if I get the go, I'll do it and announce it here when it's done as a pull request.

Note: too many posts and videos get lost in the forum, so using the manual in an efficient way can lead to greater clarity for users and farmers.

**Comment by despiegk** [comment]
I like it

**Comment by Mik-TF** [comment]
@despiegk 

Good!

I added the TF Video Gallery in this pull request: https://github.com/threefoldtech/info_grid/pull/31

I then close this issue! Thanks
