### ISSUE TITLE
RSS Feed for TF Manual

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#323]
As in [this issue](https://github.com/threefoldfoundation/www_threefold_io/issues/315) from TF Foundation, we could add an RSS functionality to the TF Manual, since the community asked for it: "A partner is asking if we have plans to introduce RSS "

@samaradel 
Do you want to have a look? You set it very quickly for threefold.io. I understand too if you're busy!

[mdbook-rss](https://gitlab.com/albalitz/mdbook-rss) could be worth looking into.

**Comment by samaradel** [comment]
referred to https://github.com/threefoldtech/info_grid/pull/328#issuecomment-1855969482

**Comment by Mik-TF** [comment]
Closing this issue as it is not possible or effective for mdbook to set RSS feed as of now.
