### ISSUE TITLE
Interstellar is a non custodial wallet

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/info_grid#326]
This notice on securing TFT holdings doesn't apply to Interstellar, because it's really just an interface to Stellar Dex and non custodial wallet. Such warning can be reserved for CEX (BTC Alpha only at this point).

https://github.com/threefoldtech/info_grid/blob/e30c4155fc1b04c74ee948a8a6bde8b894417ec8/src/threefold_token/buy_sell_tft/interstellar.md?plain=1#L39-L45

**Comment by Mik-TF** [comment]
Answered in #327
