### ISSUE TITLE
add documentation for external service contracts

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#34]

**Comment by renauter** [comment]
In which context / place would we insert such section?

What kind of doc is expected?
If I refer to what I see it seems to be a tutorial format ("how to ..."), right?

Here is what already exists on the topic for reference:
- more conceptual https://github.com/threefoldtech/tfchain/blob/development/substrate-node/pallets/pallet-smart-contract/service_consumer_contract_flow.md
- more technical: https://github.com/threefoldtech/tfchain/blob/development/substrate-node/pallets/pallet-smart-contract/third-party_service_contract.md

**Comment by Mik-TF** [comment]
Closing this issue, since it's merged and added to the manual, here: https://manual.grid.tf/tfchain/tfchain_external_service_contract.html
