### ISSUE TITLE
update grid component list?

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/info_grid#356]
update https://manual.grid.tf/concepts/grid3_components.html

some maybe new and isnt there yet and some are probably deprecated, im not quite up to date on this, mik @Mik-TF could you help on this one ? :)

**Comment by Mik-TF** [comment]
From what I understand, there is no need for any change to this section for now.

@xmonader do you think we need to update this section? Thanks.

**Comment by Mik-TF** [comment]
Maybe once we push the new dashboard, currently on dev net, to the main network, we could update the components and indicate where needed which component are now archived.

We can start now and merged to main info_grid branch when it's online on main net.

**Comment by Mik-TF** [comment]
Closing for now. We can re-open or create a new issue if we need to update the list later.
