### ISSUE TITLE
Improve Cloud section

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/info_grid#375]
Please include what's in this link https://library.threefold.me/info/threefold#/cloud/pricing. Which explains CU, SU, and NU.

**Comment by A-Harby** [comment]
Relate also https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1996

**Comment by Mik-TF** [comment]
We transferred the library cloud section to the manual: https://manual.grid.tf/wiki/cloudunits/cloudunits_toc.html

For example, see [this](https://manual.grid.tf/wiki/cloudunits/pricing/pricing.html).

I think we can improve on the section so I will simply rename the issue and then we can fix the section.

**Comment by Mik-TF** [comment]
> Relate also [threefoldtech/tfgrid-sdk-ts#1996](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1996)

Will write a new issue for this.

**Comment by Mik-TF** [comment]
Fix when #368 is merged.
