### ISSUE TITLE
Write clear TF Support Statement

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#385]
# Issue

TF Support members often get asked questions outside of TF. While they can take the time to help, it is not their obligation. TF Support should have clear disclaimer on the kind of help it can offer to users.

This issue was discussed with the communication and content circle, with @scottyeager and @amandacaster 

# Proposition

We should generate a clear statement, that we can display on the manual and elsewhere, where it is stated clearly what the TF Support can and cannot do in terms of support and help, etc.

e.g.

> The ThreeFold support team can help you with anything to do with ThreeFold. If you have questions about workloads or projects not directly related to TF, the support team can help you, but this is not part of their official functions. Please bear this in mind when contacting the TF support team.

@TullysInc 
Do you want to write something around this? I think it fits with your knowledge and experience with the support team.

**Comment by Mik-TF** [comment]
@TullysInc I assigned you for a draft and I can help to finalize. Let me know.

**Comment by TullysInc** [comment]
> @TullysInc I assigned you for a draft and I can help to finalize. Let me know.

@Mik-TF  - While I find that the statement itself is pretty straightforward (as I mentioned earlier), I presume at some point we're failing to establish where we draw the line with ThreeFold Support's jurisdiction. I state this in context to a [case ](https://github.com/threefoldtech/tf_support/issues/626), where in it's not totally clear if ThreeFold is indeed responsible for these issues, given that the WordPress deployment is on the TF Grid.

**Comment by Mik-TF** [comment]
@scottyeager @TullysInc 
Would be nice to have something on this soon. Or if it's not ready we can close the issue and work on this later.
Let me know. we could discuss about this during the next tech meeting too.

**Comment by Mik-TF** [comment]
OK! I think I have something:

The members of the ThreeFold support team are happy to help you explore the ThreeFold Grid. 
Questions you might have may fall outside of the support team's scope, e.g. if your deployments involve third parties.
Please take this into consideration when interacting with the support team.

**Comment by Mik-TF** [comment]
As discussed with the support team, we will go with the statement above, but for now we will publish it on the forum among a broader TF support post (by Sherwin).

So for now we have completed the work needed. Closing this issue. We may open a new issue later when we want to implement the broader tf support statement on the manual.
