### ISSUE TITLE
review and merge PRs in the repo

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#388]
right now it has 24 PRs

**Comment by Mik-TF** [comment]
All the non-draft PRs are from me, so I can't review them. I stay available to adjust the PRs based on the upcoming reviews.

**Comment by ramezsaeed** [comment]
WIP:
- https://github.com/threefoldtech/info_grid/pull/289
- https://github.com/threefoldtech/info_grid/pull/294
- https://github.com/threefoldtech/info_grid/pull/392
- https://github.com/threefoldtech/info_grid/pull/335
- https://github.com/threefoldtech/info_grid/pull/337
- https://github.com/threefoldtech/info_grid/pull/342

**Comment by ramezsaeed** [comment]
WIP:
- https://github.com/threefoldtech/info_grid/pull/336
- https://github.com/threefoldtech/info_grid/pull/338
- https://github.com/threefoldtech/info_grid/pull/343
- https://github.com/threefoldtech/info_grid/pull/351
- https://github.com/threefoldtech/info_grid/pull/365

**Comment by ramezsaeed** [comment]
WIP:
- https://github.com/threefoldtech/info_grid/pull/367
- https://github.com/threefoldtech/info_grid/pull/343
- https://github.com/threefoldtech/info_grid/pull/368
- https://github.com/threefoldtech/info_grid/pull/378

**Comment by A-Harby** [comment]
- https://github.com/threefoldtech/info_grid/pull/387
- https://github.com/threefoldtech/info_grid/pull/408

**Comment by khaledyoussef24** [comment]
- https://github.com/threefoldtech/info_grid/pull/419
- https://github.com/threefoldtech/info_grid/pull/412
- https://github.com/threefoldtech/info_grid/pull/410

**Comment by Mik-TF** [comment]
It is ok to close the issue, but just to be sure, there are still 4 non-draft PRs in the repo
