### ISSUE TITLE
Adjust Code of Conducts

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#393]
The code of conduct has been updated but there's still two places where we need to adjust the words used:

"[Disputes](https://www2.manual.grid.tf/contribute/code_conduct.html#disputes)
ascsac will govern any dispute related to these terms or your use of the forum.

You and the company agree to seek injunctions related to these terms only in state or federal court in city_for_disputes. Neither you nor the company will object to jurisdiction, forum, or venue in those courts."

`ascsac`
and
`cite_for_disputes`

@sabrinasadik Can you have a look please? Thanks!

**Comment by sabrinasadik** [comment]
@Mik-TF I looked into this but it's very unclear what is meant here. 

Which company are we referring to? I keep reading 'the company' ok great but which one? Once we know that we can answer the question of jurisdiction.

**Comment by Mik-TF** [comment]
I agree that it isn't clear. Here are the two main sources for this:

- https://forum.threefold.io/t/collaboration-manifesto-code-of-conduct/48
- https://forum.threefold.io/t/terms-of-service/4
   - the last link here is where the ascsac and city_for_disputes texts are to be found
   
 Initially, this issue was from threefoldfoundation: https://github.com/threefoldfoundation/info_cloud_production/issues/10

 It seems ascsac and city_for_disputes were never properly written in any case.
 
Perhaps we'd need to find who wrote this in the first place and ask for the proper terms.
 
 I don't know which came first, but there is another similar document online: https://www.usnv2.net/tos
 
 
![image](https://github.com/threefoldtech/info_grid/assets/77026219/ed86b75e-8e83-45ef-93bf-16e9652982a1)

**Comment by Mik-TF** [comment]
@sabrinasadik @xmonader 
Can we do something around this? It's been there for a while now.

We could perhaps put the previous code of conduct written by Kristof?
Or we try to fix this one. Either we know what to put in there, or we remove the section.

**Comment by Mik-TF** [comment]
"Fixed" when #436 is merged.
