### ISSUE TITLE
Protect the master branch

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/info_grid#401]
Only development branch is protected, not master. Suggest we apply the same settings (at least require review before merging PR).

**Comment by Mik-TF** [comment]
Good idea to protect it.

I think an ideal scenario would be that we can only merge master from development. IMO, theres  no need for master review if it comes from dev since dev branch requires a review.

**Comment by Mik-TF** [comment]
Concerning my proposition, if this can't be done, maybe we just make clear that we only merge master from development, which is more or less already the case. Yesterday I did a quick dev-split to master merge since Kristof wanted a simpler buy tft section.

**Comment by Mik-TF** [comment]
There's an ongoing issue where we want to restructure the manual and protecting the master branch is in the things to do.

For this reason I will close this issue as we can work on protecting the master branch in the other issue ([here](https://github.com/threefoldtech/info_grid/issues/431#issuecomment-1956937235))
