### ISSUE TITLE
Billing is fully documented

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/info_grid#424]
Is all the information here documented? I found some in the pricing calculator, but is that all covered, and is there a section for the entire billing process? 
https://gist.github.com/mohamedamer453/6ac5cdac2fb35bbf3d1462e89c8bb1e7

**Comment by Mik-TF** [comment]
Good point, there is not as much info on billing in the manual.

I will add a section Billing (the ThreeFold Billing.md from @mohamedamer453) on this page: https://manual.grid.tf/wiki/cloudunits/cloudunits_toc.html

Let me know if you have another suggestion.

**Comment by Mik-TF** [comment]
Fix when #430 is merged.
