### ISSUE TITLE
Include mycelium in docs

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/info_grid#427]
- explain what's mycelium and how to use it from both grid_client and playground.
- https://github.com/threefoldtech/mycelium

**Comment by Mik-TF** [comment]
Started to document and test: https://forum.threefold.io/t/mycelium-explorations/4225

Sharing first with the community to get their feedback. Then we could add in the manual.

**Comment by Mik-TF** [comment]
Fixed when #435 is merged.
