### ISSUE TITLE
Add dashboard button to header

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/info_grid#459]
Notes form @Mik-TF on the implementation so far:

> - Added the theme folder to be able to adjust things. The theme folder is usually created by default in the backend using mdbook build. I just initialize it and updated to add the dashboard icon top right. (mdbook init --theme). So the theme is the default theme.
> - Added a dashboard icon at the header, so user can go to the dashboard.grid.tf quickly
![image](https://github.com/threefoldtech/info_grid/assets/77026219/04191c10-cd36-45ef-bac5-af633f3528f5)

**Comment by scottyeager** [comment]
I did a bit of reading: https://rust-lang.github.io/mdBook/format/theme/index.html

Seems that adding some customizations under `theme/` is a normal mdbook pattern, but they suggest to only include the files that are actually changed.

Here's a version with the minimal changes: https://github.com/threefoldtech/info_grid/tree/development_dashboard_icon2

Using this approach means we remain eligible for most updates coming downstream to the theme, with just the one file becoming static.

**Comment by Mik-TF** [comment]
Done when #460 is merged
