### ISSUE TITLE
Document wallets related to PoU

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/info_grid#462]
Let's add info regarding wallets that are holding TFT collected during utilization.

## PoU Wallets

These wallets are on TF Chain (see pricing policy):

1. Foundation share
2. Staking pool
3. Default solution provider

Let's provide:

1. Address for each
2. How to query balance
3. How to check funds were never moved (account nonce hasn't increased)

These queries can be done in Polkadot UI.

**Comment by scottyeager** [comment]
Here's the necessary call on Polkadot UI to retrieve the wallet addresses for 1 and 3:

![image](https://github.com/threefoldtech/info_grid/assets/17682591/cb5a3004-b010-4dea-a314-4ba801f57fe3)


We can likewise extract the staking pool account from [tfchain code](https://github.com/threefoldtech/tfchain/blob/33046d68072f9972b53e92f616a8852fe107f36e/substrate-node/runtime/src/lib.rs#L396).

So the three wallets are:

```
foundationAccount: 5DCaGQfz2PH35EMJTHFMjc6Tk5SkqhjekVvrycY5M5xiYzis
Staking Pool: 5CNposRewardAccount11111111111111111111111111FSU
certifiedSalesAccount: 5Dd6adUJH8wvqb9SPC96JdZ85nK1671MeMSxkPZ6Q7rE4byc
```

We can check the balance and nonce as so:

![image](https://github.com/threefoldtech/info_grid/assets/17682591/c40e4e8e-7f29-44fd-8231-92136a4bc779)

Note that this is for mainnet only. Testnet also uses real TFT and has it's own wallets for the two that aren't hard coded:

```
foundationAccount: 5H6XYX17yJyjazoLVZqxxEPwMdGn99wginjmFBKtjvk8iJ3e
certifiedSalesAccount: 5Esq6iLLBGGJFsCEXpoFhxHhqcaGqTvDasdwy8jPFDH1jYaM
```

**Comment by Mik-TF** [comment]
Complete when #478 is merged.
