### ISSUE TITLE
Outdated flists in the `Supported FLists` section

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/info_grid#47]
### Description

Flists available in https://manual.grid.tf/manual3_iac/grid3_supported_flists.html needs to be updated.

- `Ubuntu` flist is `https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-20.04.flist` the latest one is `https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-22.04.flist`
- `k3s` flist is `https://hub.grid.tf/ahmed_hanafy_1/ahmedhanafy725-k3s-latest.flist` the official one is `https://hub.grid.tf/tf-official-apps/threefoldtech-k3s-latest.flist`

**Comment by 0oM4R** [comment]
should we add more flists that are already in https://github.com/threefoldtech/tf-images/tree/development/tfgrid3 ?

**Comment by 0oM4R** [comment]
I think it will be better to make the links refers to https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-22.04.flist.md not download the flist directly

**Comment by mohamedamer453** [comment]
Verified from www2.manual.grid.tf

The Supported Flists page was updated with links for the official flists.

![image](https://user-images.githubusercontent.com/101194226/230892865-77ce1c39-9d86-41c7-8976-4ce3dd6e87fb.png)


and as mentioned in the comment above now the links redirect the user to the ZOS hub page of the flist instead of downloading it which greatly improves the experience.
