### ISSUE TITLE
[10.1 Threefold Complete Farming Guide] The `Creating the Farm on Threefold Grid` section is completely outdated.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/info_grid#48]
### Description 

[10.1 Threefold Complete Farming Guide] The `Creating the Farm on Threefold Grid` section is completely outdated.

The [`Creating the Farm on Threefold Grid`](https://manual.grid.tf/TF_Farmer_Guide/TF_Complete_Farmer_Guide/farmer_guide.html#2-creating-the-farm-on-threefold-grid) section is completely outdated since it still uses links and screenshots from `portal.grid.tf`

**Comment by Mik-TF** [comment]
I'll take care of this during the week. @mohamedamer453

**Comment by mohamedamer453** [comment]
> I can take care of this during the week. @mohamedamer453
> 
> Let me know.

Sure thing it would be great if you could, Thanks!

**Comment by Mik-TF** [comment]
The changes have been done and they are available in this [pull request](https://github.com/threefoldtech/info_grid/pull/61).

This issue can be closed. Or we wait until the PR is accepted.

**Comment by Mik-TF** [comment]
The farming documentation has been updated with the last PR.

https://www2.manual.grid.tf/TF_Farmer_Guide/TF_Complete_Farmer_Guide/farmer_guide.html

I thus close this issue!
