### ISSUE TITLE
Broken Links in the `Getting Started` Page

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/info_grid#49]
### Description

The first 4 links in the [`Getting Started`](https://manual.grid.tf/getstarted/tfgrid3_getstarted.html) page are broken.

- [Install Polkadot Widget](https://manual.grid.tf/dashboard/portal/dashboard_portal_polkadot_widget.html)
- [Create and Activate account](https://manual.grid.tf/dashboard/portal/dashboard_polkadot_create_account.html)
- [Activate Twin](https://manual.grid.tf/dashboard/portal/dashboard_ui_activation.html)
- [TFT to TFChain](https://manual.grid.tf/dashboard/portal/dashboard_ui_tokens.html)

**Comment by 0oM4R** [comment]
handled by f7ba9dbdeaf55bff04619bee53a2c0d0bc670fb3

**Comment by 0oM4R** [comment]
this issue somehow is outdated, locally, and `www2.manual.grid.tf` the mentioned titles were removed

![image](https://user-images.githubusercontent.com/62248851/227784579-23245035-2be9-49e0-9e18-8f986c30f6dd.png)

**Comment by Mik-TF** [comment]
@0oM4R indeed.

This issue should be closed as the new changes fix it.
