### ISSUE TITLE
Missing docs for zlogs and cloud-console

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/info_grid#499]
## Description

Currently, there are no documentation for how to use zlogs or cloud-console. There are some docs describing what they are but not how to use them. We should include usage of zlogs and cloud-console with their requirements and setup.

**Comment by Mik-TF** [comment]
# References for the Issue

- cloud-console: https://github.com/threefoldtech/zos/blob/main/docs/manual/zmachine/cloud-console.md
- zlogs: https://github.com/threefoldtech/zos/tree/main/docs/manual/zlogs, https://github.com/threefoldtech/zos/blob/main/pkg/gridtypes/zos/zlogs.go

**Comment by Mik-TF** [comment]
I am currently testing cloud-console to document properly.

Raised an [issue](https://github.com/threefoldtech/zos/issues/2267) as I can't access cloud-console based on the documentation from zos repo.

Will be able to finish this info_grid issue once cloud-console works as documented or more info comes in.

**Comment by Mik-TF** [comment]
cloud-console is accessible properly on devnet. should be soon merged to main and test nets.

Will be able to continue this issue for cloud-console.

**Comment by Mik-TF** [comment]
Complete when #527 is merged.

**Comment by Mik-TF** [comment]
@AbdelrahmanElawady Oh well! I just saw that you've been assigned yesterday! Maybe #527 can help you complete this then.
Feel free to not take any work I did, or to adjust the PR I made. 

Thanks!

**Comment by AbdelrahmanElawady** [comment]
@Mik-TF It's all good. I think I might have been assigned here by mistake anyway. But I'll take a look at the PR. Thanks!
