### ISSUE TITLE
[10.1 Threefold Complete Farming Guide] The `Check 3node Status on the TF Explorer` section is completely outdated

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/info_grid#50]
### Description

[10.1 Threefold Complete Farming Guide] The [`Check 3node Status on the TF Explorer`](https://manual.grid.tf/TF_Farmer_Guide/TF_Complete_Farmer_Guide/farmer_guide.html#2-check-3node-status-on-the-tf-explorer) section is completely outdated since it's using links and screenshots from the old explorer.

**Comment by MohamedElmdary** [comment]
@mohamedamer453 I was going to update the docs but it seems to be up to date already however it shows an old version in the website
here is what I see in the `development` branch in docs
![image](https://user-images.githubusercontent.com/31689104/227926750-d2e0c8d8-7338-4600-94dd-ae55bc102cc3.png)

**Comment by Mik-TF** [comment]
This should be corrected with the new pull request in the dev branch.

https://www2.manual.grid.tf/TF_Farmer_Guide/TF_Complete_Farmer_Guide/farmer_guide.html#2-check-3node-status-on-the-tf-explorer

This issue could be closed then.

**Comment by mohamedamer453** [comment]
Verified from www2.manual.grid.tf

Indeed the section was updated with the new dashboard/explorer links.

![image](https://user-images.githubusercontent.com/101194226/230907974-8239c5ac-b9b2-4505-9beb-75dc3ed56d0f.png)
