### ISSUE TITLE
Update manual with new Dashboard changes

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/info_grid#507]
- Dedicated Nodes page should be removed from the manual
- Update Node Finder page with new UI changes

**Comment by Mik-TF** [comment]
@zaelgohary do we have the official UI of the node finder ready? Or things may change?

Once we know we have the final UI for node finder page, I can do this PR and put it as a draft for when it hits mainnet/testnet

**Comment by Mik-TF** [comment]
# Info to add

Note for the PR:

Add that the network speed test is updated every 6 hours on the dashboard.

**Comment by Mik-TF** [comment]
WIP: testing cloud-console first. Some issue detected and documented [here](https://github.com/threefoldtech/zos/issues/2267)

Will update this issue as things get fixed.

**Comment by Mik-TF** [comment]
Complete when #514 is merged
