### ISSUE TITLE
[2.3. Threefold Dashboard] The steps for creating a twin should be updated

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/info_grid#51]
### Description

[2.3. Threefold Dashboard](https://manual.grid.tf/getstarted/TF_Dashboard/TF_Dashboard.html) The steps for creating a twin should be updated, to replace the twin ip creation part with selecting the relay.

![image](https://user-images.githubusercontent.com/101194226/227219773-9af86bf1-5331-4769-9316-ee2862ec2f2b.png)

**Comment by 0oM4R** [comment]
Creating an account should be updated in many other places, I will make it a separate file and mention it before every needed section.

**Comment by mohamedamer453** [comment]
Verified on www2.manual.grid.tf

The twin creation steps was updated with the new flow and also as mentioned in #57  the video will also be updated with the relay once it's available on mainnet and the screenshots will also be updated with mainnet's relay.
