### ISSUE TITLE
[7.1. Profile Manager] section is outdated

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/info_grid#52]
### Description

[7.1. Profile Manager](https://manual.grid.tf/weblets/weblets_profile_manager.html) section is outdated and needs to replaced with the current look and functionality of the profile manager.

and the same thing for [7.1.1. Profile Manager Unlock](https://manual.grid.tf/weblets/profile_manager_unlock.html)

**Comment by mohamedamer453** [comment]
The [docs](https://www2.manual.grid.tf/weblets/weblets_profile_manager.html#process) still mention the `Activate` button which was removed from the profile manager.

![image](https://user-images.githubusercontent.com/101194226/230894048-636d38a7-7354-4b1d-99e2-8183e56a01b9.png)

**Comment by xmonader** [comment]
docs of the playground will be redone in 3.11

**Comment by xmonader** [comment]
obsoleted by the new playground #120
