### ISSUE TITLE
Show to wrap mnemonics in quotes for farmerbot cli

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/info_grid#530]
Note from the community is that it would be helpful to show that seed phrases need to be wrapped in quotes when doing an operation like this one:

https://github.com/threefoldtech/info_grid/blob/5d7fda2bb694cb779f2f573932a19506a57979e7/src/documentation/farmers/farmerbot/farmerbot_information.md?plain=1#L93

**Comment by Mik-TF** [comment]
So this?

farmerbot start --node <node ID> -m "<mnemonic>" -n dev -d

Not needed for -n or --node argument?

**Comment by Mik-TF** [comment]
Can close when #532 is merged
