### ISSUE TITLE
Update server side for dev branch hosting

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/info_grid#535]
# Situation

We updated the dev branch workflow. We want the manual dev branch to be published on www.manual.dev.grid.tf instead of www2.manual.grid.tf

See the new workflow: https://github.com/threefoldtech/info_grid/blob/development/.github/workflows/manual_update_development.yml

# Todo

- Update the server+DNS hosting the manual so it goes to www.manual.dev.grid.tf instead of www2.manual.grid.tf

@xmonader

**Comment by Mik-TF** [comment]
For now dev branch can't be built with workflow since the workflow points to manual.dev.grid.tf.

![image](https://github.com/threefoldtech/info_grid/assets/77026219/6b16f142-5035-4d5b-be96-67f58c596d41)

**Comment by Mik-TF** [comment]
@sabrinasadik do you think you can set this?
Let me know if you need more info.
Thanks!

**Comment by Mik-TF** [comment]
I set the priority to major since the new dashboard (3.13) is now on mainnet. Thus we want to make sure the manual is updated and goes to main branch.

**Comment by sabrinasadik** [comment]
@hossnys can you pls check on sunday? Thx

**Comment by hossnys** [comment]
fixed , and re-run for workflow triggered and deployed successfully except the broken link check as there are some wrong urls.

![Screenshot from 2024-05-26 14-32-21](https://github.com/threefoldtech/info_grid/assets/26298009/7ea1b436-67de-4256-a909-fcf618493652)

**Comment by Mik-TF** [comment]
Thanks!! Yes I will fix the URLs asap

**Comment by Mik-TF** [comment]
@hossnys looks like I should have set manual.dev.grid.tf instead of www.manual.dev.grid.tf. Will make a quick PR to fix this.
Otherwise writing manual.dev.grid.tf on the browser doesn't work, we need to add www.

**Comment by hossnys** [comment]
yes , as you only requested www.manual.dev.grid.tf , let me add another dns record for manual.dev.grid.tf

**Comment by Mik-TF** [comment]
Oh! OK that would work then. Also I just made a PR: https://github.com/threefoldtech/info_grid/pull/546

Thanks a lot!!

**Comment by hossnys** [comment]
added manual.dev.grid.tf dns record also .

**Comment by Mik-TF** [comment]
It works! thanks a lot. 

![image](https://github.com/threefoldtech/info_grid/assets/77026219/281e8e4b-a28d-4b86-88d4-2507adec8c35)

Closing this and the other now unnecessary PR.
