### ISSUE TITLE
Add troubleshooting section to main farming section

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/info_grid#555]
Currently there is only farming troubleshooting under the FAQ. While there's lots of good info there, it's easy to miss when drilling down the nav menu and also could provide a bit more of a structure approach to troubleshooting.

Here's a high level of what I'm imagining:

1. Build troubleshooting (how to wipe disks, BIOS config steps, etc)
2. Basic post build troubleshooting (reboot node, reboot router, check the network signal path)
3. Advanced post build troubleshooting (connect a screen and look for errors, then info on how to address certain errors)
4. How to get further assistance (contact support team/use the farmers chat for community support)

**Comment by Mik-TF** [comment]
Updated: 
![image](https://github.com/threefoldtech/info_grid/assets/77026219/cb39537d-5279-4c83-bf98-e33fbf25289d)
