### ISSUE TITLE
what should we do with the old manual?

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/info_grid#56]
- if this one is the uptodate one, people will still go to the old one, in few weeks, it will be a big problem.

**Comment by rkhamis** [comment]
It should be kept as is, according to Kristof. we will not be updating it

**Comment by sasha-astiadi** [comment]
are we duplicating a lot of stuff in manual vs in here?
maybe we should remove the ones that are updated here?

**Comment by Mik-TF** [comment]
Good question.

The new mdbook is way faster.

We can also take what is good in the old manual and update the new.

I can work on this if needed. Let me know.

**Comment by Mik-TF** [comment]
We could also create a second mdbook for the Library.
We can simply transfer the actual library to a new mdbook.

It's just faster compared to publish tools. And publish tools isn't updated/ready to work fast.

**Comment by sasha-astiadi** [comment]
@Mik-TF hi mik thanks a lot, will contact you on telegram, maybe we can have a chat on how to move forward

**Comment by sasha-astiadi** [comment]
me and karoline discussed with kds , he wanna  take down the old one and just keep the new one @rkhamis @xmonader @sabrinasadik @Mik-TF and please let dev know. 

<img width="1120" alt="Screenshot 2023-05-03 at 14 25 21" src="https://user-images.githubusercontent.com/43240801/235914901-f5af9783-ad23-447a-ba8e-529c27a67519.png">

and here is my proposal on how we could move forward:
we need to slowly take down the old manual instead of taking it down at once, just in case we still need some information on the old one, that havent been transferred yet to the new manual.

**- suggesting users to go to new manual**
- [ ] add the new manual link on the old manual homepage for now and suggest users to go to the new manual
- [ ] replace the old manual links on TF website with the new one

**- proofread old manual**
- [ ] get web team and support team to proofread old manual, find duplicated articles that have been transferred to new one, as well as the articles that have not been transferred to the new one
- [ ] transfer old issues from old manual repo to the new one
- [ ] provide list of old articles that have not been transferred to the new one, and discuss with dev team on what's deemed necessary to include to the new manual
- [ ] transfer old articles to the new one , only if necessary

**deactivate the old manual**
- [ ] after transfer is finished, ask ops to redir manual.threefold.io to the new manual.grid.tf
- [ ] keep old manual repo as archived

**Comment by Mik-TF** [comment]
In "documentation", I think the first point is already done:
"make a tutorial on how to use mdbooks and add it to the new manual"

See this section of the new manual: https://www2.manual.grid.tf/contribute/contribute.html

If this is sufficient, we can check this task.

@sasha-astiadi

**Comment by sasha-astiadi** [comment]
based on our research, its shown that all displayed files in old manuals form the navbar  are successfully migrated
