### ISSUE TITLE
TF Robot docs for dashboard

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/info_grid#563]
there is a new application is added to dashboard which is need a separated docs other than the sdk docs.
it should redirect to another docs for using the machine or the deployment in the dashboard section not the developers section.
may this docs also containt tfcmd , tf-grid-cli ,tf robot which are also installed on the vm.

**Comment by Mik-TF** [comment]
Will add this for dev net manual until it's available on main net. Will work on this next week.
