### ISSUE TITLE
Updated farmerbot 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/info_grid#569]
Farmerbot has a new feature node priority where farmers get to specify the order in which their standby nodes wake up: https://github.com/threefoldtech/tfgrid-sdk-go/issues/978.

Also, the thresholds have been updated to check each resource, and farmers can set them: https://github.com/threefoldtech/tfgrid-sdk-go/issues/804.

**Comment by A-Harby** [comment]
Also can't find any docs for this telegram bot feature https://github.com/threefoldtech/tfgrid-sdk-go/issues/987

**Comment by Mik-TF** [comment]
@A-Harby good!

Node status bot (last point you mentioned) is now here: https://manual.grid.tf/documentation/farmers/node_status_bot/node_status_bot.html

Will check the 2 other things.

**Comment by Mik-TF** [comment]
Fixed when #571 is merged.
