### ISSUE TITLE
Farmerbot log management

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/info_grid#579]
As time goes on, the farmerbot log file will grow rather large. This makes it difficult to work with, and can eventually become a concern of taking up too much disk space So it would be nice to add some info on strategies for managing the logs.

One simple suggestion is just copying the latest entries from the log file into a new file. This can be useful for log review or for sharing logs when older entries are not relevant. Here's an example command to copy the latest 1000 lines into a new file:

```
tail -n 1000 farmerbot.log > farmerbot-recent.log
```

Beyond that, it would be nice to present some ways of rotating the log file to keep its size down. Some ideas to explore:

* Using the `logrotate` service
* Sending the logs into `journald` instead of sending them directly to a file, then using `journald` methods for log rotation (vacuum). This would also require providing additional docs on how to view and share these logs, since they would no longer be in an easily accessible file

**Comment by scottyeager** [comment]
Here are some additional findings regarding `logrotate`:

* Generally speaking, processes are going to continue writing into the old log file when logs are rotated, even if that file is moved
* Many programs support a `SIGHUP` signal that causes the program to reopen its logfile (and also reload its config). This is the best way to handle log rotation, but I don't think farmerbot supports it yet
* As a fallback, the `copytruncate` option can be given to `logrotate`. This provides a similar effect, but comes with a risk that some log entries are lost, if logs are being written at the same time as the rotate operation

So this gives a few possible paths:

1. Just suggest `logrotate` with `copytruncate` for now. If logs are rotated weekly or monthly and there's occasionally a few lines lost on the boundaries, this is probably acceptable
2. Request an update to farmerbot to allow more graceful rotation using `SIGHUP` (also reloading the config file on this signal would be a nice feature too)
3. Push the logs to `journald` and document needed functions like dumping the logs to a file

In the end, I wanted to use a log file rather than `journald` to keep things simple, but it might be that's actually the simplest option after all.

**Comment by Mik-TF** [comment]
Good! Let's go with a first "version" with journald then!

**Comment by Mik-TF** [comment]
We can close when #589 is merged
