### ISSUE TITLE
Docs for the new solutions implanted in the dashboard

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/info_grid#590]
docs needed for the 2 new applications in the dash board 
- GitTea
- Nostr
- 
<img width="480" alt="Screenshot 2024-07-03 at 2 55 41 PM" src="https://github.com/threefoldtech/info_grid/assets/110984055/e9f625c6-4e79-46ae-ac30-fc5ab476b38c">
<img width="493" alt="Screenshot 2024-07-03 at 2 55 44 PM" src="https://github.com/threefoldtech/info_grid/assets/110984055/b0717fce-8a80-403c-89d2-a86fd6869102">

**Comment by Mik-TF** [comment]
It'll be my pleasure to add those 2 apps.

Great work by the dev team for bringing this up.

**Comment by Mik-TF** [comment]
WIP: https://github.com/threefoldtech/info_grid/pull/592/files

**Status**

- Waiting to see if we implement some new features before documenting
  - https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2010#issuecomment-2209279379
  - https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2015#issuecomment-2209259470

**Comment by khaledyoussef24** [comment]
nice job is done here @Mik-TF I will wait until they re-release them

**Comment by Mik-TF** [comment]
Good! Once its updated I will adjust the guides accordingly. Should be quick at this time.

**Comment by Mik-TF** [comment]
We can close when #594 is merged
