### ISSUE TITLE
booting nodes specially with no-sdd disks fails to boot

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/info_grid#591]
Sometimes nodes with no-ssd disks failed to boot with `no disks registration failed` even if we pass `missing-sdd` kernel param
the solution for this was to change the sata settings in boot to use `AHCI`

**Comment by ashraffouda** [comment]
already handeled in the docs

**Comment by Mik-TF** [comment]
That was a quick one :P

Thanks @ashraffouda
