### ISSUE TITLE
"Add  a Domain" Section

### ISSUE THREAD

**Issue by Marinaa-Emad** [threefoldtech/info_grid#601]
### There is "Add  a Domain" Section in the Manual and it doesn't exist in ThreeFold website :

![add domain](https://github.com/user-attachments/assets/19311828-cd04-4295-a7ac-926aed14e494)

![threefold](https://github.com/user-attachments/assets/201a3c7c-65de-45e1-86a1-ae5b1f19395e)

**Comment by Mik-TF** [comment]
Users can add a domain to their deployment as stated in the guide.

Are you saying we should move this elsewhere? Not sure I understand. thanks.

**Comment by Mik-TF** [comment]
To be clear, once users deployed a VM, they can add a domain: 
![image](https://github.com/user-attachments/assets/6625597b-5c8f-4fff-a07c-e219c7befd67)

**Comment by Mik-TF** [comment]
Tried to make more sense of it all in #605

If you think it's OK @Marinaa-Emad, we can then close this issue when the mentioned PR is merged. Thanks
