### ISSUE TITLE
Min Disk Size in Micro Virtual Machine

### ISSUE THREAD

**Issue by Marinaa-Emad** [threefoldtech/info_grid#602]
### Disk Size should be Min 15 and in Threefold website it accepted numbers less than 15 :

![disk size](https://github.com/user-attachments/assets/73ca7b51-3af5-4e75-bd20-3b6a3d6cdf21)

![disk](https://github.com/user-attachments/assets/0a81090f-c6c9-4aea-8a18-8130a9da2902)

**Comment by Mik-TF** [comment]
Minimum disk size for micro VM is 15GB as I just tested on main and dev nets:

![image](https://github.com/user-attachments/assets/83532944-bd9f-4bae-b647-fa0b509e2ad0)

One way or another, we don't state that the min is 15GB on the manual, so it's OK.

Can we close the issue? @Marinaa-Emad  Thanks

**Comment by Mik-TF** [comment]
The min you tested is in Disks so that's the mount point. Indeed it can be lower than 15GB. But for the Config section, the minimum is 15GB.

LMK if we need to change anything to the manual.

**Comment by Mik-TF** [comment]
@Marinaa-Emad any news on this? Thanks!

**Comment by Mik-TF** [comment]
I will close for now.
