### ISSUE TITLE
Min CPU and Memory in Node Pilot card

### ISSUE THREAD

**Issue by Marinaa-Emad** [threefoldtech/info_grid#603]
### In Node Pilot card: Min CPU should be 8 and Min Memory should be 8192 but both in Threefold website accepted values less than these

![fail2](https://github.com/user-attachments/assets/15aa57b7-b8cf-4ff1-a744-5dc65b34df3e)

![fail3](https://github.com/user-attachments/assets/ff227e5f-42cf-46a7-ae57-a6b377cb8d9e)

**Comment by Mik-TF** [comment]
Fixed in #604
