### ISSUE TITLE
Gitea docs is missing

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/info_grid#606]
The link to [Gitea](https://www.manual.grid.tf/documentation/dashboard/solutions/gitea.html) on the dashboard is missing on the manual
![image](https://github.com/user-attachments/assets/93ad4fc6-1256-44b3-abd4-c43df044905f)
![image](https://github.com/user-attachments/assets/6c1eef4b-2f68-47b3-bd40-7bc66ad2ce8c)

**Comment by Mik-TF** [comment]
It's in manual.dev.grid.tf for now. Just merged to master manual.grid.tf for simplicity.

**Comment by Mik-TF** [comment]
To be clear, the link is working now.
