### ISSUE TITLE
Document for a farmer how to find the node logs/statistics

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#615]
if exists please link me to it

**Comment by Mik-TF** [comment]
Checking with @scottyeager.
Will report on this issue or make a PR with necessary changes if needed.

**Comment by Mik-TF** [comment]
To be clear, do you want us to add something on how farmers can access a node public Grafana page? Or you are talking of something else, maybe perhaps public page for logs?

**Comment by xmonader** [comment]
There's a link in the node details  (Check node health)
![image](https://github.com/user-attachments/assets/0148bcad-d690-40ff-8ad7-2f7ef9f7bc17)
that gets the farmer to this dashboard 
![image](https://github.com/user-attachments/assets/103ba0e1-5c9b-4b8c-9c06-904b9958e2af)

but there's also another link that I don't remember @coesensbert or @scottyeager  maybe remembers to get the logs of  certain node

**Comment by scottyeager** [comment]
We have logs on mon.grid.tf, but that's not a public service. I'm not sure that node logs should be public. Providing the farmer a way to access the remotely stored logs for only their own nodes would be nice. I don't think it's possible without a lot of work though.

**Comment by coesensbert** [comment]
https://mon.grid.tf/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

You can access Loki collected logs via mon.grid.tf indeed, but this whole Grafana instance is here for internal use only.
We could add the ZOS Loki backend for example to metrics.grid.tf but limiting access (if that would be required) will be quite difficult. By default, anyone will be able to see any node logs. So depends what is required here.

**Comment by Mik-TF** [comment]
OK for now I will show the public grafana access then.

**Comment by Mik-TF** [comment]
So we already show a link to the Node Finder in the Farmers section:

![image](https://github.com/user-attachments/assets/daf9c10c-d5ba-4be1-9aa2-b620f6034995)

What I will do is add a step on the Node Finder section to show users/farmers they can click on Node Health to go to the Grafana page.

**Comment by Mik-TF** [comment]
LMK if #621 is sufficient. If yes, we can close this issue.
