### ISSUE TITLE
add a note for opentofu in the manual

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#616]
as a truly open source alternative / compatible with terraform (add how to install and how to invoke)

**Comment by Mik-TF** [comment]
Do we want to add a new section OpenTofu below Terraform here?
![image](https://github.com/user-attachments/assets/8cf5107f-4aef-41da-8b83-dbb9eb9a0941)
With sections on:

- installation
- deployment examples
- etc.

Or we just put a mention in Terraform section stating that OpenTofu is compatible with Terraform?

Can be something else too. Lmk.

Thanks.

**Comment by Mik-TF** [comment]
Went with a basic approach as suggested.

We can close when #620 is merged, if it's sufficient of course.
