### ISSUE TITLE
add mycelium support in all of the docs

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#617]
- [x] terraform
- [x] pulumi
- [x] typescript
- [x] golang sdk
- [x] tfcmd
- [x] tfrobot

let's make sure it's documented and clearly linked

**Comment by Mik-TF** [comment]
# Status

- WIP: https://github.com/threefoldtech/info_grid/pull/638

# Todo

- Once the repos are updated with Mycelium examples, we can update the manual with the updated examples and then close this issue.

**Comment by Mik-TF** [comment]
@xmonader do we want to do the same we are doing for pulumi, terraform, go and javascript, but for TFROBOT and TFCMD? (add info on using mycelium)

**Comment by Mik-TF** [comment]
# Update

- Devs are doing great progress on all related issues to add info on mycelium
- Once all the issues are closed, we can finalize the PR associated to this specific issue and close the issue.

**Comment by Mik-TF** [comment]
# Update

- I think everything is OK here and we can continue the PR. Still waiting for the 3 issues opened above to be closed to be sure.
- Will update when we have news on the 3 issues themselves.

**Comment by Mik-TF** [comment]
# Update

- All PRs needed to complete the docs are merged.
- Will now update the PR for this info_grid docs update for mycelium

**Comment by Mik-TF** [comment]
Done and merged in #638
