### ISSUE TITLE
Enable Jitsi & Jenkins docs in Dashboard

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/info_grid#637]

**Comment by zaelgohary** [comment]
As the [Jitsi's PR](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3346) is merged now. Can we enable the Jitsi route in the Dashboard? @Mik-TF

**Comment by Mik-TF** [comment]
It is already available in dev manual: manual.dev.grid.tf

But I went ahead and merged it to manual.grid.tf master. 

So all good. Thanks.
