### ISSUE TITLE
Missing Documentation: Prerequisites for Installing Guardian Stack on a VM

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/info_grid#641]
While following the instructions for deploying a new Guardian stack on a VM

https://manual.grid.tf/documentation/developers/grid_deployment/grid_deployment_full_vm.html

**the documentation should include instructions for installing the following prerequisites:**

1. Git
2. Rust
3. apt update
4. Subkey

**Comment by khaledyoussef24** [comment]
<img width="1680" alt="Screenshot 2024-09-16 at 4 41 54 PM" src="https://github.com/user-attachments/assets/f2288d46-7eb7-4bf8-b4f3-e9a880fe4b93">
while installing the subkey i face this error so i can not proceed
it worked before but may be the upgraded version of ubuntu 24 does not support it
stuck on this  to continue testing the gurdian stack
https://github.com/threefoldtech/tf_operations/issues/2754

**Comment by Mik-TF** [comment]
@khaledyoussef24 seems that subkey was moved from docker-compose folder to apps folder: https://github.com/threefoldtech/grid_deployment/commit/63d455b443b929c91510b7be817393705a72ab49

Can you retry with this? I will update the docs.
