### ISSUE TITLE
Update `SMTP Server` docs

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/info_grid#645]
As [#3398](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3398) 
Now the ```Admin Email``` field can support ```Username``` too, please update it.

**Comment by Mik-TF** [comment]
Good. Will check this. It is relevant for those apps right?

- discourse
- taiga
- gitea
- mattermost

Please lmk if there's more.

**Comment by Mik-TF** [comment]
@samaradel made a simple PR based on the discussion in [#3398](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3398).

LMK if it's sufficient or if we need more changes.

**Comment by samaradel** [comment]
@Mik-TF Perfect! let's apply it to the rest apps docs.

**Comment by Mik-TF** [comment]
Done. Please review if possible the PR #649
