### ISSUE TITLE
Updated suggested based on feedback from advisors: part 2

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/info_grid#650]
We have gotten some feedback from advisors on the following:

1. Remove all "non-technical," non-essential, and non-relevant documentation, anything which could be seen as inconsistent or anything that needs updating (then re-add later) – let's go "less is more" and "better safe than sorry" approach for now

Best to do this on a branch and we verify with @despiegk.

**Comment by Mik-TF** [comment]
Ok. I need more info on point 1.

 2 and 3 are clear.

**Comment by Mik-TF** [comment]
Set part 1 and part 2:

- part 1: **https://github.com/threefoldtech/info_grid/issues/651**
- part 2: this one

**Comment by Mik-TF** [comment]
# PRs

- For part 2: https://github.com/threefoldtech/info_grid/pull/652
- For part 1: can do when we have more info

**Comment by samtaggart** [comment]
Hi @Mik-TF the feedback on the above is:

"To make it simple i would simply hide for now: https://manual.grid.tf/knowledge_base/about/about.html – so the entire "about" section until we improve it. I believe the rest is ok."

... which it seems has already been done in the PR. I think release notes are fine to keep. (But they should be updated, no? The last ones are from July 2023.)

**Comment by Mik-TF** [comment]
OK good then I will set the PR as a non-draft. We can create another issue to update the release notes.
