### ISSUE TITLE
Update Grid Full VM Deployment Section

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/info_grid#655]
Now the manual will only point you on how to deploy the stack using the script, but I had some issues while using the script it would have been a lot easier to know what did the script do or manual steps to follow instead of the script; which would have helped me to catch the error.

Also, some more info is found here that is not found in the manual.
https://github.com/threefoldtech/grid_deployment/tree/development/docker-compose#deploy-a-full-stack

**Comment by A-Harby** [comment]
Can we also mention that the script is downloading 3 large files and extracting them? Download first, then extract it, and then the second, and so on.

And the extracting takes a long time, and its done after that line with no info about that happening (and it takes hours!). 
![image](https://github.com/user-attachments/assets/35ddb4c3-c246-41b7-b91b-4e11e7b97c57)

**Comment by Mik-TF** [comment]
Hey @A-Harby! Good point, we can definitely improve the manual concerning this. Can you give more info?

Are you talking about this? https://manual.grid.tf/documentation/developers/grid_deployment/grid_deployment_full_vm.html#launch-the-script

There is no link to the manual in your issue. Thanks!

**Comment by Mik-TF** [comment]
OK good. What is the errors you encountered? Then we can document and the full_vm guide and explain how to troubleshoot.
Were you deploying with full vm on the grid?

I will check back the process and adjust the documentation in the manual and the script itself, e.g. we share the link to the script and we explain what it does briefly, and the script could print messages to the users with info on the progress.

**Comment by A-Harby** [comment]
1. There should be a step-by-step to deploy the stack (the only option now is the script) or at least a description for the script.
2. There should be a very clear note that the script will take hours to download and extract all the files (and showing the progress would be a lot better, but the note is still necessary).
3. The script downloaded and extracted all the files on the root no matter your pwd, which caused me a lot of issues until I figured it out and had to update the paths manual in the script to my current location (it would be nice to add a path option). 
4. It would be nice to mention where the stacks environment version is coming from and how to update (it says we shouldn't in the file, idk why).
5. After a successful installation, we should mention how to see the logs of our stack.

That's it for now.

**Comment by Mik-TF** [comment]
Amazing feedback. Will check this soon with @coesensbert 

Thanks @A-Harby

**Comment by A-Harby** [comment]
Also found that there's a script for installing the prerequisites; it would also be great to mention those.

**Comment by Mik-TF** [comment]
Completed when #659 is merged.

**Comment by coesensbert** [comment]
all but the script logic applied here: https://github.com/threefoldtech/grid_deployment/commit/0b4b279c15b11379db633b4fc91363d0f1bd5943

**Comment by A-Harby** [comment]
Still getting some error but gonna retry again.

![image](https://github.com/user-attachments/assets/6987fe33-794f-489b-8fe0-aae437a12d64)

**Comment by Mik-TF** [comment]
Are you deploying on the grid with a Full VM with modern hardware?

**Comment by A-Harby** [comment]
I was able to finally deploy the stack after multiple failures in the downloads; I had to do each manually, and also, after finishing the script, it didn't work I had to wait for a while, and I don't why.

But it did work, and here is the link: dashboard.harby.gridtesting.xyz.

And I have also added both your keys, @coesensbert and @PeterNashaat to the VM if you want to check to make sure everything is fine.

**Comment by PeterNashaat** [comment]
- The tfchain public node is fully operational and synced.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/49727c91-728d-4e0b-9dd7-d19f3be34fd0">

- The processor is also successfully synced.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e2f82034-dfe4-4f68-b0d0-4b5318850658">

- The dashboard is functioning as expected, listing contracts, available nodes, and farms.
- Found some errors in gridproxy 
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/fce323f8-60a8-4e45-9321-a5a0e7c583f2">

- Also found error messages in the relay.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/51b983e0-19b7-46ad-9611-a164eda8922c">

**Comment by Mik-TF** [comment]
# Update

- In the last week, Bert (and I to some extent) worked on the TFGrid Full Stack docs on the grid_deployment repo: https://github.com/threefoldtech/grid_deployment
- The procedures and docs in that repo is now complete.
- This makes some of the manual sections outdated.
- I think it's better to just have a section on the manual explaining broadly the TFGrid Full Stack components and then to link from the manual to the grid_deployment repo's docs. This will make it easier for updates and improvements as we won't be needing to adjust 2 sets of independent docs.
- Conclusion, I will create another simpler PR linking to the grid_deployment docs instead of having it all on the manual.
  - This means this PR won't be needed anymore: https://github.com/threefoldtech/info_grid/pull/659
  - We didn't lose any time as we could troubleshoot the process. I hope everyone understands. LMK if you want to proceed otherwise.

**Comment by Mik-TF** [comment]
As explained above, closing in favor or #663

**Comment by A-Harby** [comment]
I opened an issue for the retry and update all the scripts, https://github.com/threefoldtech/grid_deployment/issues/91.

**Comment by Mik-TF** [comment]
Thank you for this @A-Harby!

**Comment by A-Harby** [comment]
I had the same errors on the testnet proxy IDK why, but the relay didn't show any.

![image](https://github.com/user-attachments/assets/1d16299a-7b60-48cf-8058-070051a61cf4)

![image](https://github.com/user-attachments/assets/bbde019b-aafc-4615-9e67-f84246c3c3cc)

**Comment by coesensbert** [comment]
> I had the same errors on the testnet proxy IDK why, but the relay didn't show any.
> 
> ![image](https://private-user-images.githubusercontent.com/109473873/378845118-1d16299a-7b60-48cf-8058-070051a61cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDE5MTAsIm5iZiI6MTcyOTYwMTYxMCwicGF0aCI6Ii8xMDk0NzM4NzMvMzc4ODQ1MTE4LTFkMTYyOTlhLTdiNjAtNDhjZi04MDU4LTA3MDA1MWE2MWNmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxMjUzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDAxYzNiNzJiZTI5MjY2ODY1NzQwODIzNjM4ZWM1ZTYxOTc3ODYzMjg3ODZhZGE2YWE3M2E3ZWFhNTE4NTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nVEJpIMYJOW0f8SBetKw7IiTGk2HC0A8vvAXD12z4lQ)
> 
> ![image](https://private-user-images.githubusercontent.com/109473873/378845557-bbde019b-aafc-4615-9e67-f84246c3c3cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDE5MTAsIm5iZiI6MTcyOTYwMTYxMCwicGF0aCI6Ii8xMDk0NzM4NzMvMzc4ODQ1NTU3LWJiZGUwMTliLWFhZmMtNDYxNS05ZTY3LWY4NDI0NmMzYzNjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxMjUzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmUwMDBjMWI5MWMxZGNhNDM3MzA2OTI1YWE1MjIyNDE3YjNmNzEwZDcyYjhhNjI4ZDliMmU2NDdmY2M1Y2UzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iJIOSgfC7jvgt6ulZ5GIq2CrLeUyyfiMpUglTnINGZA)
> 
> @PeterNashaat @coesensbert, Also the dashboard, working fine creating accounts or sending and receiving requests.

or the time on the server is not correct, or the tfchain node your running is not fully synced.
I'm guessing the latter since we can see it here: https://telemetry.tfchain.grid.tf/#list/0x0378abe88c21bd382106e7977902eef4f542bb2d3e67e8a318151e323b2d0660

**Comment by Mik-TF** [comment]
# Update

- The manual now links to the grid_deployment docs: https://www.manual.grid.tf/documentation/developers/grid_deployment/tfgrid_full_stack.html
- This means we can work on grid_deployment repo instead of info_grid for anything related to full stack deployment
- Let's close this one and work on the grid_deployment issue: https://github.com/threefoldtech/grid_deployment/issues/91
