### ISSUE TITLE
Remove Liquidity Provider section of the manual (for now)

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/info_grid#656]
https://manual.grid.tf/documentation/threefold_token/liquidity/liquidity_readme.html

- There are some inaccuracies (e.g. 1inch is an aggregator, )
- We do not have a real effort or strategy right now around LP
- Something we will / should add back, but right now it is not adding any particular value

cc: @Mik-TF will ping you privately on TG

**Comment by Mik-TF** [comment]
Completed when #657 is merged.
