### ISSUE TITLE
Add info about How to Create a Stellar Wallet on LOBSTR

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/info_grid#669]
This document is how to create a stellar account, fund it, and add a TFT trustline from stellar itself. It would be useful to have it in the manual too, i think.
https://docs.grid.tf/threefold/itenv_threefold_main/src/branch/master/docs/create_stellar_wallet.md

**Comment by Mik-TF** [comment]
Hi! It is really nice docs, but we currently have a basic lobstr + stellar wallet/account guide: https://manual.grid.tf/documentation/threefold_token/storing_tft/lobstr_wallet.html

It was decided to keep the manual section on TFT as simple as possible, so I don't think we want/need to put any more in there. LMK what you think.

**Comment by A-Harby** [comment]
Does the app have an option for testnet or only mainnet?

**Comment by Mik-TF** [comment]
Not that I am aware of. As I understand it's just for mainnet. 

LMK what you think. If you want to add this to the manual, it could be in the developers section in a section called Advanced Wallet section perhaps.

**Comment by xmonader** [comment]
No need to cover beyond mainnet for the official manuals, anything that's internal to the team or to the internal testing shouldn't go there.
