### ISSUE TITLE
Threefold connect app Manual should be updated to match latest release.

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/info_grid#688]
https://manual.grid.tf//documentation/tfconnect/tfconnect_advanced.html

As we now have a new release for threefold connect  app; the manual should be updated including screenshots from the new app.

Also adding kyc verification steps is strongly needed to be clear in the manual.

**Comment by Mik-TF** [comment]
Thanks for creating the issue.

- The KYC part is already covered here: https://manual.grid.tf//documentation/dashboard/tfchain/kyc.html
- Will update the manual with TF Connect app soon

**Comment by ramezsaeed** [comment]
There is also KYC on the app itself too; not only dashboard now, which should be covered in the app manual as well

**Comment by Mik-TF** [comment]
@ramezsaeed do you mean email verification?

It is covered in this part of the guide now: https://www3.manual.grid.tf/documentation/tfconnect/tfconnect_installation.html#email-verification

From PR: https://github.com/threefoldtech/info_grid/pull/700

LMK if it's sufficient or please give me more info. Thanks!

**Comment by Mik-TF** [comment]
OK just saw your other reply.
