### ISSUE TITLE
Update dedicated node info with rentable or rented node filter

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/info_grid#705]
As https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2775, Now we support displaying the rented dedicated nodes and the other dedicated ones that are available for the user to rent in the same switch, please check the image below:

![image](https://github.com/user-attachments/assets/05691865-9995-46dc-85ae-974116b214e2)

**Comment by Mik-TF** [comment]
@samaradel done. btw that is a very GREAT idea. It really makes the deployment way easier.
