### ISSUE TITLE
[9.2. TFChain Portal]: broken link for the `Transfer TFT` section

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/info_grid#71]
### Description

https://www2.manual.grid.tf/dashboard/portal/dashboard_portal_home.html#transfer-tft

The link for `Transfer TFT` docs is broken and redirects to https://www2.manual.grid.tf/dashboard/portal/dashboard_portal_ui_tokens.html

![image](https://user-images.githubusercontent.com/101194226/233348991-6c7ad7e8-75e8-4460-a0cd-e020a412ad09.png)

**Comment by Mik-TF** [comment]
The link is now working and this [link](https://www2.manual.grid.tf/dashboard/portal/dashboard_portal_ui_tokens.html) does lead to a section of the tutorial that shows how to transfer tft from tfchain to stellar.

Closing this issue.

Will create a new issue asking to put all the TFT bridges, transfers, etc. in the same section.
