### ISSUE TITLE
Missing Docs

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/info_grid#73]
The following links are missing:
- https://library.threefold.me/info/threefold#/cloud/threefold__pricing?id=dedicated-servers
- https://library.threefold.me/info/threefold/#/tfgrid/grid/pricing?id=discount-levels
- https://library.threefold.me/info/manual/#/
- https://library.threefold.me/info/manual/#/manual__grid3_stellar_tfchain_bridge
- https://library.threefold.me/info/manual/#/manual__tfchain_home
- https://library.threefold.me/info/manual/#/manual__weblets_TFhubValidator

**Comment by Mahmoud-Emad** [comment]
For the Manual, the link exists there, check https://manual.grid.tf/getstarted/tfgrid3_getstarted.html

**Comment by Mahmoud-Emad** [comment]
1- /cloud/cloudunits_pricing.html#dedicated-servers
2- /cloud/cloudunits_pricing.html#discount-levels
3- /getstarted/tfgrid3_getstarted.html
4- /advanced/grid3_stellar_tfchain_bridge.html
5- /tfchain/tfchain.html

Maybe the last one does not require, you can update these links with the `manual.grid.tf` after the pr got merged.

**Comment by khaledyoussef24** [comment]
found in the new staging docs 
![image](https://github.com/threefoldtech/info_grid/assets/110984055/6ed96ce7-be31-4250-9c0e-0f81d035f17c)
