### ISSUE TITLE
Document advanced networking for farms with public IPs 

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/info_grid#78]
@scottyeager added a FR on the old manual https://github.com/threefoldfoundation/info_manual3/issues/156

# Document advanced networking for farms with public IPs  

For farmers who have public IPs, extra considerations are needed in setting up the network of the farm. Currently this is not covered in the manual, but we do have some older docs in the Zos repo (see [here](https://github.com/threefoldtech/zos/blob/master/docs/network/setup_farm_network.md)). There's also advice shared by community members such as [this forum post](https://forum.threefold.io/t/node-1655-does-not-seem-to-be-connected-correctly/3685/11).

The goal is to bring the existing documentation into the manual, get it up to date, and expand it to cover the most common cases. Farmers in a data center environment will have less control over their network, and are also the most likely to have public IPv4s available.

## Some scenarios
DC provides a network link into the farmer's rack. The farmer provider their own router and switch
DC provides a router and/or switch in the rack
Gateway IP provided is in the same range as the public IPs
Gateway IP is in a different range than the public IPs
Farmer segments the OOB ("Zos"/private) interfaces and the public interfaces into separate VLANs or uses separate switches altogether
No segmenting is actually necessary, farmer connects all interfaces to one switch

## Overall requirements
Provide DHCP to one interface for each node
Ensure that public IPs are routable from at least one interface
That's it?

## Notes and warnings
Never expose lights out management interfaces to public internet
Does it matter which NICs are used?
How can farmer test the setup is legit? Need to deploy a workload, either with gateway or public IP reserved to see that it's working (future versions of network will do better automatic validation)

## Configuring interfaces over RMB
There's a program floating around that allows farmers to configure the interfaces on their nodes. This is done over RMB, and I also developed a script for this purpose. Both might be deprecated with the 3.9 release and new RMB. There should be a documented way of doing this that's relatively accessible.

--

perhaps its a useful suggestion for the new manual. pls ignore if not applicable

**Comment by Mik-TF** [comment]
" program floating around that allows farmers to configure the interfaces on their nodes. This is done over RMB, and I also developed a script for this purpose."

Any news on either the program or the script?

Working on this issue in [this branch](https://github.com/threefoldtech/info_grid/tree/development_advanced_networking).

Could be useful to add! Thanks.

**Comment by Mik-TF** [comment]
Fixed in #320
