### ISSUE TITLE
FAQs > Who are the co-founders of Threefold? > Broken Link

### ISSUE THREAD

**Issue by Ashishban** [threefoldtech/info_grid#83]
There is a broken link for [Christopher Hutton](https://www.threefold.io/people/christopher-hutton/) also we do not have Christopher's name mentioned on the [co-founders](https://threefold.io/memberships/cofounders/) page of the website.

URL on FAQ - https://manual.grid.tf/faq/faq.html#who-are-the-co-founders-of-threefold

**Comment by Mik-TF** [comment]
Next week, I will work on all your issues starting with prefix FAQs (issues #83 to #88).

We focused on getting the books done and re-organized (farmers, devs, sysadmins) lately.
It's time to put some attention to the broken links, etc.

Thanks!

**Comment by Mik-TF** [comment]
This has been fixed. Closing. Thanks!
