### ISSUE TITLE
FAQ > How is Threefold registered as an entity? > Links redirect to old manual

### ISSUE THREAD

**Issue by Ashishban** [threefoldtech/info_grid#84]
URL - https://manual.grid.tf/faq/faq.html#how-is-threefold-registered-as-an-entity

All the read more hyperlinks on this FAQ redirects to old manual, we may have to create the pages for these links and then make the changes :

https://library.threefold.me/info/legal/#/orgstructure/threefold__threefold_vzw
https://library.threefold.me/info/legal/#/threefold__threefold_dubai

**Comment by Mik-TF** [comment]
Will be fixed when https://github.com/threefoldtech/info_grid/pull/321 is merged

**Comment by Mik-TF** [comment]
Fixed in #321
