### ISSUE TITLE
FAQ > What is Proof-of-Utilization? > Links redirect to old manual

### ISSUE THREAD

**Issue by Ashishban** [threefoldtech/info_grid#85]
URL - https://manual.grid.tf/faq/faq.html#what-is-proof-of-utilization

Hyperlinks on this FAQ redirects to old manual for Proof of Utilization and discounts, we may have to create the pages for these links and then make the changes :

https://library.threefold.me/info/manual/#/tfgrid/farming/threefold__proof_of_utilization
https://library.threefold.me/info/manual/#/tfgrid/farming/threefold__staking_discount_levels

**Comment by Mik-TF** [comment]
Will be fixed when https://github.com/threefoldtech/info_grid/pull/321 is merged

**Comment by Mik-TF** [comment]
Fixed in #321
