### ISSUE TITLE
FAQs > How does Proof-of-Utilization work? > Links redirect to old manual

### ISSUE THREAD

**Issue by Ashishban** [threefoldtech/info_grid#86]
URL - https://manual.grid.tf/faq/faq.html#how-does-proof-of-utilization-work-how-is-the-threefold-token-tft-distributed-when-there-is-utilization-on-the-threefold-grid

Hyperlinks on this FAQ redirects to old manual for 3Node, Zero-Os, TF-Chain, DAO, discount mechanism, TFTs and Proof of Utilization charts, we may have to create the pages for these links and then make the changes :

https://library.threefold.me/info/manual/#/tfgrid/farming/threefold__zos
https://library.threefold.me/info/manual/#/tfgrid/farming/threefold__3node
https://library.threefold.me/info/manual/#/tfgrid/farming/threefold__tfchain
https://library.threefold.me/info/manual/#/tfgrid/farming/threefold__dao
https://library.threefold.me/info/manual/#/tfgrid/farming/threefold__staking_discount_levels
https://library.threefold.me/info/threefold#/tokens/threefold__token_overview

**Comment by Mik-TF** [comment]
Will be fixed when https://github.com/threefoldtech/info_grid/pull/321 is merged

**Comment by Mik-TF** [comment]
Fixed in #321
