### ISSUE TITLE
FAQs - What is the maximum supply of Threefold tokens? - Broken Link and Redirecting to old manual

### ISSUE THREAD

**Issue by Ashishban** [threefoldtech/info_grid#87]
URL - https://manual.grid.tf/faq/faq.html#what-is-the-maximum-supply-of-threefold-tokens-what-is-the-current-supply-of-threefold-tokens

Read more hyperlink doesnt open and redirects to old manual - https://library.threefold.me/info/threefold#/tokens/threefold__stats_token_overview_farmed

**Comment by Mik-TF** [comment]
Will be fixed when https://github.com/threefoldtech/info_grid/pull/321 is merged

**Comment by Mik-TF** [comment]
Fixed in #321
