### ISSUE TITLE
FAQs: Issues with Redirection, Broken Links and Others

### ISSUE THREAD

**Issue by Ashishban** [threefoldtech/info_grid#88]
URL - https://manual.grid.tf/faq/faq.html#what-is-the-network-information-to-access-bsc-for-the-threefold-token-what-is-the-token-address-for-adding-the-token-in-the-metamask-app

Hyperlink redirects to old manual - For more information, read [this](https://library.threefold.me/info/threefold#/tokens/threefold__tft_bsc_metamask).

--------------------------------------------------------------------------------------------------------

URL - https://manual.grid.tf/faq/faq.html#how-can-i-filter-3nodes-by-country-and-by-network-ipv4-ipv6-and-planetary-network

Hyperlink for See this Explorer by Teisie doesnt work - https://www.app-yoke.com/explorer.html

--------------------------------------------------------------------------------------------------------

URL - https://manual.grid.tf/faq/faq.html#can-i-deploy-a-mastodon-server-on-threefold-grid

Hyperlink redirects to old manual - Check this easy-to-follow guide right [here](https://library.threefold.me/info/manual/#/manual__threefold_mastodon_home).

--------------------------------------------------------------------------------------------------------

URL - https://manual.grid.tf/faq/faq.html#what-is-threefolds-cloud-pricing-are-there-any-discounts-available-for-threefolds-cloud-pricing

Hyperlink redirects to old manual - Threefold cloud pricing and discounts [here](https://library.threefold.me/info/threefold#/tfgrid/pricing/threefold__pricing).

--------------------------------------------------------------------------------------------------------

URL - https://manual.grid.tf/faq/faq.html#the-gateways-are-advertised-as-many-to-many-how-can-i-have-more-than-one-gateway-assigned-to-a-deployment-can-more-gateways-be-added-after-deployment

No hyperlink on Webgw (also missing 2.0) as old manual says it is [WebGW 2.0](https://library.threefold.me/info/manual/#/threefold__webgw)

--------------------------------------------------------------------------------------------------------

URL - https://manual.grid.tf/faq/faq.html#how-can-i-create-a-profile-manager-on-the-threefold-playground

Hyperlink redirects to old manual - For the detailed steps, read [this documentation](https://library.threefold.me/info/manual/#/manual__weblets_profile_manager)

 --------------------------------------------------------------------------------------------------------

URL - https://manual.grid.tf/faq/faq.html#i-want-to-deploy-a-virtual-machine-vm-on-threefold-how-can-i-do-this

Hyperlink redirects to old manual - Read this [short documentation](https://library.threefold.me/info/manual/#/manual__weblets_vm)

 --------------------------------------------------------------------------------------------------------

URL - https://manual.grid.tf/faq/faq.html#how-can-i-deploy-kubernetes-on-the-threefold-grid

Hyperlink redirects to old manual - Read [this documentation](https://library.threefold.me/info/manual/#/manual__weblets_k8s) to find out.

 --------------------------------------------------------------------------------------------------------

URL - https://manual.grid.tf/faq/faq.html#how-can-i-deploy-peertube-on-the-threefold-grid

Hyperlink redirects to old manual - You can learn more about this [here](https://library.threefold.me/info/manual/#/manual__weblets_peertube).

 --------------------------------------------------------------------------------------------------------

URL - https://manual.grid.tf/faq/faq.html#how-can-i-deploy-owncloud-on-the-threefold-grid

Hyperlink redirects to old manual - Read the [documentation here](https://library.threefold.me/info/manual/#/manual__weblets_owncloud) to learn more.

 --------------------------------------------------------------------------------------------------------

URL - https://manual.grid.tf/faq/faq.html#how-can-i-use-and-install-yggdrasil

Hyperlink redirects to old manual - Learn all about this [here](https://library.threefold.me/info/manual/#/manual__yggdrasil_client).

 --------------------------------------------------------------------------------------------------------

URL - https://manual.grid.tf/faq/faq.html#how-can-i-rent-or-reserve-a-3node-dedicated-node-server-on-the-threefold-grid-what-are-the-main-steps-when-deploying-workloads-on-a-dedicated-node

Bullets not properly alligned

<img width="520" alt="Screenshot 2023-05-05 025410" src="https://user-images.githubusercontent.com/91247662/236333356-7b48b981-46ef-415e-86fc-0553a205bc41.png">

 --------------------------------------------------------------------------------------------------------

**Comment by Mik-TF** [comment]
Will be fixed when #321 is merged

**Comment by Mik-TF** [comment]
Fixed in #321
