### ISSUE TITLE
Menu bar doesn't stick when scrolling

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/info_grid#89]
I think the currently published manual is affected by https://github.com/rust-lang/mdBook/issues/2028.

Compare manual.grid.tf:

![image](https://user-images.githubusercontent.com/17682591/236354273-5be05d40-0a4a-4b6e-bebc-f6dc012d2b25.png)

With https://rust-lang.github.io/mdBook:

![image](https://user-images.githubusercontent.com/17682591/236354331-501cf749-ad12-47f2-9b51-786ff48097d7.png)

If we're running mdbook v4.27 then it looks like an update to v4.28 should fix this.

**Comment by khaledyoussef24** [comment]
the menu bar now sticks 
![Screenshot from 2023-05-10 10-06-42](https://github.com/threefoldtech/info_grid/assets/110984055/407047e0-4d24-4572-8136-e5ebe2e5ab38)
![Screenshot from 2023-05-10 10-06-36](https://github.com/threefoldtech/info_grid/assets/110984055/b98a6c68-6bb1-415f-9208-0fa293f60c9d)
