### ISSUE TITLE
missing tutorial: Nixos Micro VM deployment tutorial missing

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/info_grid#94]
hello, im not sure if its still applicable or not, not sure if we still offr this solution or not, but web team is doing research and found a lot of articles are not in the new manual...

 the tutorial:
[Nixos Micro VM](https://library.threefold.me/info/manual/#/manual__weblets_nixos_micro?id=nixos-micro-vm)
![nixos](https://github.com/threefoldtech/info_grid/assets/43240801/bb177f2c-4713-425e-9238-19343c0a3a1e)

i can help to move it if we still do it you can assign to me, if not pls just close this issue thank you

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldtech/info_grid/pulls

**Comment by Mik-TF** [comment]
Done in last [PR](https://github.com/threefoldtech/info_grid/pull/113) with you @sasha-astiadi 

Thanks. Closing this issue.
