### ISSUE TITLE
missing section: Infrastructure As Code

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/info_grid#96]
# background story
we are moving relevant articles from old manual to new manual because we wanna archive the old one after migration is completed.

issue:
https://github.com/threefoldfoundation/info_manual3/issues/176

# issue

not sure if its still applicable or not, not sure if we still offr this solution or not, but web team is doing research and found a lot of articles are not in the new manual... for example this one [Infrastructure As Code](https://library.threefold.me/info/manual/#/manual__manual3_iac_home).

if code owners accept this FR, id gladly help to make this one just assign to me, thank you

**Comment by Mik-TF** [comment]
Done in last PR. Closing the issue.
